### ISSUE TITLE
Server deployment with data loaded on localhost

### ISSUE THREAD

**Issue by Tinchossh** [horilla-opensource/horilla#108]
# Bug Report

## Description

I want to know how to deploy to a server without losing the data loaded on localhost. I also want to know how to import the database. I am not sure if the database is also copied when deploying.

## Expected Behavior

To be able to deploy to the server, keeping everything loaded on localhost

## Environment

- **Django Version:** _[Django version you're using, e.g., 3.2.1]_
- **Python Version:** _[Python version,3.12]_
- **Operating System:** _[Windows 11]_
- **Browser:** _[Opera version: 107.0.5045.36 , Edge Version 122.0.2365.66 (Official build) (64-bit) ]_

**Comment by horilla-opensource** [comment]
Hi @Tinchossh ,
In case you are using the sqlite3 database for the your use, you can copy the database file from your local instance and paste it inside the horilla directory in your server and change the name of the database inside the settings.py to the name of your database.
Or else if your are using the psql database, you can make use of the dump of the database and restore it in your server using the psql commands and change the settings inside the settings.py which you can see inside the [README.md](https://github.com/horilla-opensource/horilla/blob/master/README.md).

With Regards,
**Team Horilla**

**Comment by Tinchossh** [comment]
** Thanks!!!!!!!!!!!!
