### ISSUE TITLE
[Feature Request] Mobile Application

### ISSUE THREAD

**Issue by Guhan-SenSam** [horilla-opensource/horilla#109]
# Feature Request

Hi @horilla-opensource Team

Hi I was wondering what where the plans for any mobile applications. The current backend is not api first but it seems that it can be easily modified to serve both html templates and as api endpoints using headers to distinguish between which one is requested.

I have experience in developing both android only and cross platform(android+ios) mobile applications at scale and would love to contribute if there are any plans for mobile development.

Regards,
Guhan

**Comment by horilla-opensource** [comment]
Hi @Guhan-SenSam ,
We are already under the mobile application development for which our design team is currently creating the app design and another team is working on the rest api for the modules.
We'll add the api's developed till now into a separate branch by next week to which you can have a look into and add your suggestions to it.
Thanks for your interest and cooperation in contributing to Horilla.
We'll keep you posted on the updates on it.

With Regards,
**Team Horilla**

**Comment by Guhan-SenSam** [comment]
Cool will definitely look into it when the API's become available and the designs for the app have been finalized.
Thank you
Guhan

**Comment by mulberry111** [comment]
Any update on the rest api code?

**Comment by horilla-opensource** [comment]
Hi @mulberry111 ,
We'll add a separate repo for the API and will share the current development status in that by next week at the most.

With Regards,
**Team Horilla**

**Comment by Abenezer** [comment]
first of all thanks for this beautiful project. 
and any new updates on the rest api?  (i an not seeing  the api branch )

**Comment by horilla-opensource** [comment]
Hi @Guhan-SenSam ,
The app is released to the play store: https://play.google.com/store/apps/details?id=com.cybrosys.horilla_project&pcampaignid=web_share

Please check and share your feedabacks.

**Comment by horilla-opensource** [comment]
> first of all thanks for this beautiful project. and any new updates on the rest api? (i an not seeing the api branch )

Hi @Abenezer @mulberry111  ,
The rest api system is now in the master. You can check that out.

**Comment by M35a2** [comment]
I am loving the mobile app so far. 
i was wondering if it was open source? I cannot seem to find the repo for it. 
I was hoping i could fork it and add some feature that is specific to my organizations needs.

**Comment by horilla-opensource** [comment]
Hi @M35a2 ,

Thanks for the feedback. It's always great to hear that our product is being loved by other.

The mobile app is also open source. The repo will be made public by this week or next week starting.

We are making some short  marketing videos for it. Once that's done, the repo will be made public asap.

With Regards,
**Team Horilla**

**Comment by M35a2** [comment]
> Hi @M35a2 ,
> 
> Thanks for the feedback. It's always great to hear that our product is being loved by other.
> 
> The mobile app is also open source. The repo will be made public by this week or next week starting.
> 
> We are making some short marketing videos for it. Once that's done, the repo will be made public asap.
> 
> With Regards, **Team Horilla**

awesome! super excited for it. 
appreciate all your team is doing!

**Comment by horilla-opensource** [comment]
Hi @M35a2 ,

The mobile app code is now public.

Please find the repo at [Horilla Mobile](https://github.com/horilla-opensource/HorillaMobile) .

Please share your thoughts and feedback on the same.

With Regards,
**Team Horilla**
