### ISSUE TITLE
Update Test Database

### ISSUE THREAD

**Issue by ashwanthbalakrishnan5** [horilla-opensource/horilla#111]
# Bug Report

## Description

Migrate Test Database for the PR's #104 and #107 

## Additional Information

Couldn't migrate as it has exsiting values in django_migrations table. Has to be done from your side.

## Priority

Low

**Comment by horilla-opensource** [comment]
Hi @ashwanthbalakrishnan5 ,
Updated the test database in the repo.
Please check.

With Regards,
**Team Horilla**

**Comment by ashwanthbalakrishnan5** [comment]
Updated, Thanks
