### ISSUE TITLE
Static Files? (Documentation issue)

### ISSUE THREAD

**Issue by CodeMouse92** [horilla-opensource/horilla#129]
# Bug Report

## Description

Documentation does not describe how to appropriately configure static files. If I do not change `STATIC_ROOT` (as it is not documented in the setup instructions), I get...

```
/opt/horilla/venv/lib/python3.10/site-packages/django/core/handlers/base.py:61: UserWarning: No directory at: /static/
```

If I follow the article about this (which doesn't give clear instructions either) and change it to something like `BASE_DIR / 'staticfiles'`, and create the `staticfiles` directory in my Horilla directory, it appears to work (having another bug, reported separately). Is this the correct way to do this?

Either way, can this be documented?

## Environment

- **Django Version:** 5.0.3
- **Python Version:** 3.10
- **Operating System:** Ubuntu 22.04

**Comment by horilla-opensource** [comment]
Hi @CodeMouse92 ,
Sorry for the issue in the documentation and thanks for pointing it out.
We'll update it asap and add it the repo.

With Regards,
**Team Horilla**

**Comment by CodeMouse92** [comment]
When I used the current settings section and default static file route, I got the error stated.

(I have not been having fun.)

**Comment by horilla-opensource** [comment]
Hi @CodeMouse92 ,
We are extremely sorry for the issues you have been facing while setting Horilla up.
Our team is checking on the issue, and we'll update you asap with a solution for this.

With Regards,
**Team Horilla**

**Comment by horilla-opensource** [comment]
Hi @CodeMouse92 ,
Refer the doc in the link for installation guide while going to production.
[Horilla Deployment Guide](https://drive.google.com/file/d/1P8-OMH-ST6TQM3n2QDs2LqcgzW-ragUb/view?usp=sharing)

With Regards,
**Team Horilla**
