### ISSUE TITLE
How to: Change languages?

### ISSUE THREAD

**Issue by borishinzer** [horilla-opensource/horilla#13]
How can I change the language either based on client and/or company and/or recruitments?

**Comment by horilla-opensource** [comment]
Hi @borishinzer,
Currently the user can change the language to his required language from the language selector in the navigation bar on top.
We are updating the system for supporting more languages.
The surrent system contains Arabic, English, French, German and Spanish.

**Comment by borishinzer** [comment]
Cool. Somehow this doesn't work for German. We will also try to contribute better German translations as merge request soon.

**Comment by horilla-opensource** [comment]
Sure, thanks.
Could you specify where you found the translations not working in German, so that we can also make a walk around of it?

With Regards,
**Team Horilla**

**Comment by borishinzer** [comment]
I checked the django.po file inside horilla/locale/de/LC_MESSAGE/ and found existing translations. If I change in the GUI in the heather to German, nothing changes. As I have only minimal knowledge of python, I can't really help to debug the issue. But one of my colleagues has more knowledge. We are mainly focussed on PHP-based products such as TYPO3 or Magento. Nevertheless I found some issues in the file eg. dublicate double quotes on translations. Idk if this could break the complete translation, so I will try to fix the translation file to best knowledge. 

<img width="1424" alt="Bildschirmfoto 2023-07-28 um 20 25 05" src="https://github.com/horilla-opensource/horilla/assets/10340538/532fa773-98d6-4118-b878-106430d34887">

**Comment by horilla-opensource** [comment]
Hi @borishinzer ,
We think its because the mo file was not getting loaded.
Please run the below command and restart the service to check with the translations.

`python3 manage.py compilemessages`

With Regards,
**Team Horilla**

**Comment by borishinzer** [comment]
I got the feeling that the errors in the locale file broke the translation. After I changed the file and fixed some duplicate double quotes, it seems to work now. I also create a PR for my changes. 

**Question**: At the end of the file there are some commented strings. I would assume they would not be considered for translation.  Can I simply c&p existing English text from the GUI and add it to the localization file to create a translation, or is there more to know? Example: "New Joining Today" on the Dashboard is yet not in the file. Can I translate it like this?
<img width="1395" alt="Bildschirmfoto 2023-07-29 um 14 31 52" src="https://github.com/horilla-opensource/horilla/assets/10340538/465c9cb6-dec7-4283-b4da-ae8b0527bda6">

**Comment by horilla-opensource** [comment]
Hi @borishinzer ,
The translation for the dashboard elements are already added in the PO file and is working in the system.
We'll check with the system in the local and confirm the working after reviewing and merging your PR.
With Regards,
**Team Horilla**

**Comment by horilla-opensource** [comment]
<img width="1710" alt="Screenshot 2023-07-31 at 10 53 28 AM" src="https://github.com/horilla-opensource/horilla/assets/131998600/eebe0efa-6fb8-4ebb-bc8b-ba6d71e67892">

As you can see from the screenshot, the translation terms for the dashboard were already added in the PO files, but it is missing in the PO you updated.
Could you please check with that?
We'll also update it from our side.
With Regards,
**Team Horilla**

**Comment by horilla-opensource** [comment]
Also on checking the repo you forked, it seems that you have forked another repository which was forked from our main repo and the repo that you forked is not upto the date because of which the file you have are not updated completely.
Also we face issues with merging the pull request because of this inconsistencies.

**Comment by borishinzer** [comment]
Will do most likely next weekend.
