### ISSUE TITLE
[FEATURE] Bulk approval for overtimes and validations

### ISSUE THREAD

**Issue by borishinzer** [horilla-opensource/horilla#132]
# Feature Request
As a HR manager I want to be able to select all time entries of at employee,
so I can validate them or approve the overtimes with a bulk action.

**Comment by horilla-opensource** [comment]
Hi @borishinzer ,
Sure will add that.

With Regards,
**Team Horilla**

**Comment by horilla-opensource** [comment]
Hi @borishinzer ,
There is already feature for bulk approval. Please check the attached video.
For selecting all records of a particular employee, you can make use of the group by feature with which you can easily filter records of employees.
[BULK APPROVAL DEMO](https://drive.google.com/file/d/19RSNTeopq6saUPqz6fe0ZSSEr05MP7PN/view?usp=sharing)

Please check and let us know.

With Regards,
**Team Horilla**

**Comment by borishinzer** [comment]
Perfect. Works like a charm. 👍

**Comment by horilla-opensource** [comment]
Thanks 😍.
