### ISSUE TITLE
ModuleNotFoundError: No module named 'django.utils.datetime_safe' django

### ISSUE THREAD

**Issue by darshmashru** [horilla-opensource/horilla#133]
# Bug Report

## Description

ModuleNotFoundError: No module named 'django.utils.datetime_safe' django

## Steps to Reproduce

1. Installing Horilla using the Shell Script provided. (https://www.horilla.com/docs/installation-using-shell-script/)
```./horilla_install_ubuntu.sh #for Ubuntu```

2. Connecting to Horilla on port 8000.

OR

1. Using Docker to run Horilla (https://github.com/horilla-opensource/horilla/blob/master/docker.md)
```docker compose up``` 

2. Connecting to Horilla on port 8000.

## Expected Behavior
It should open the login page for Horilla

![image](https://github.com/horilla-opensource/horilla/assets/61720185/06b50d99-64e9-4a42-94cf-3aceb997b7c8)

## Actual Behavior

It shows the message "Internal Server Error"

In the logs it shows:
```ModuleNotFoundError: No module named 'django.utils.datetime_safe' django```

## Screenshots
![image](https://github.com/horilla-opensource/horilla/assets/61720185/a907831c-75d8-46b5-9ca1-05f44d697481)

## Environment

- **Django Version:** 5.0.4
- **Python Version:** 3.10
- **Operating System:** Ubuntu 22.04.1
- **Browser:** Arc 1.36.0

## Additional Information

I think the reason this is happening is because django.utils.datetime_safe module has been removed in Django v5.0 (https://github.com/django-haystack/django-haystack/issues/1902).  Django version has been set to v4.2.11 on the Release Tag (https://github.com/horilla-opensource/horilla/commit/098634caff474c998f83b11828732f554fb47c7e)

## Possible Solution
You can try one of the 3 possible solutions:
1. You can wait for the next release because it will be fixed for sure in the next release.
2. You can manually change the requirements.txt file and change Django>-4.2 to Django==4.2.11
3. You can use the Stable Release Tag (https://github.com/horilla-opensource/horilla/commit/098634caff474c998f83b11828732f554fb47c7e)

## Labels
Bug

## Priority

Medium

**Comment by horilla-opensource** [comment]
Hi @darshmashru ,
Thanks for pointing out the issue, the requirements files was overwritten from a commit and we haven't noticed it.
We have updated the requirements file with changes in the Django version details.
Please check.

With Regards,
**Team Horilla**

**Comment by darshmashru** [comment]
Perfect, I saw the commit (https://github.com/horilla-opensource/horilla/commit/6460fd19b9d4abfe505db45517a565453f58857a) and this issue ideally should now be fixed and should work for everyone installing Horilla using the shell script provided or Docker.
