### ISSUE TITLE
Email Configuration | Something Went error | Pls fix it

### ISSUE THREAD

**Issue by sanjaysys** [horilla-opensource/horilla#137]
# Bug Report

## Description

Hi Team,

While Configuration of email server that is not sending any mail

As per documentation email configuration code is not available in setting.py file

where we can change hostname and email related.

**Comment by horilla-opensource** [comment]
Sure,
We'll update you with the resources.

**Comment by sanjaysys** [comment]
one more issue when i am installing in windows throught command getting some error i will show you attached picture also 


and when installing in ubuntu everything is working fine. 
![Screenshot 2024-04-10 155514](https://github.com/horilla-opensource/horilla/assets/159676415/cfc28af4-092e-48ea-bf42-c1f19408bcdf)

**Comment by horilla-opensource** [comment]
Hi @sanjaysys ,
From the log , it seems to be an issue with the numpy package.
Can you try to install the numpy package using the command
`pip install numpy`
After the installation try the Horilla installation again.

With Regards,
**Team Horilla**

**Comment by sanjaysys** [comment]
Okkay thanks Sir

**Comment by horilla-opensource** [comment]
Hi @sanjaysys ,
Can we close this issue now?

With Regards,
**Team Horilla**
