### ISSUE TITLE
User Password is not received while create new user or add new employee.

### ISSUE THREAD

**Issue by sanjaysys** [horilla-opensource/horilla#138]
# Bug Report

## Description

Hi Team,

While we have create new user or employee their password has not been received to user email.

**Comment by horilla-opensource** [comment]
Hi @sanjaysys ,
By default, the user password will be the user's phone number, which on after first login, the respective user can change from the settings.

With Regards,
**Team Horilla**

**Comment by sanjaysys** [comment]
> Hi @sanjaysys , By default, the user password will be the user's phone number, which on after first login, the respective user can change from the settings.
> 
> With Regards, **Team Horilla**


Okk fine 

but what is the username if by default password is mobile

**Comment by horilla-opensource** [comment]
Hi @sanjaysys ,
The username is the user's email address.

**Comment by sanjaysys** [comment]
okkay thanks

**Comment by sanjaysys** [comment]
Okkay I have one question more basically ca we connect our biometric device into this portal through API it is possible or not

**Comment by horilla-opensource** [comment]
Hi @sanjaysys ,
Yes it is possible to connect your biometric device into Horilla.
Currently we have intergrated ZKTec devices which is through python sdk and Anvis devices which is from their API services provided.

Similarly you can integrate your preferred biometric devices into Horilla using the respective API of the devices.

With Regards,
**Team Horilla**

**Comment by sanjaysys** [comment]
have you any documents for configuration i have only essl biometric api and how can add this into horilla

**Comment by horilla-opensource** [comment]
Hi @sanjaysys ,
The ZKTeco integration will work for the essl devices also.
We'll share the biometric app with you by tomorrow.
You just need to the add the device details and ports into the system and it'll automatically sync the attendances from the device.

With Regards,
**Team Horilla**

**Comment by sanjaysys** [comment]
Sure sir please share thank you so much

**Comment by sanjaysys** [comment]
> Hi @sanjaysys , The ZKTeco integration will work for the essl devices also. We'll share the biometric app with you by tomorrow. You just need to the add the device details and ports into the system and it'll automatically sync the attendances from the device.
> 
> With Regards, **Team Horilla**

Can you Share the file for essl integration


email: rajat2013cool@gmail.com

**Comment by horilla-opensource** [comment]
Hi @sanjaysys ,
There was a small issue in the module, which the team is working on now.
Will share it with you once its rectified.

With Regards,
**Team Horilla**

**Comment by sanjaysys** [comment]
Hi Team,

Pelase share biometric module.

**Comment by sanjaysys** [comment]
> Hi @sanjaysys , There was a small issue in the module, which the team is working on now. Will share it with you once its rectified.
> 
> With Regards, **Team Horilla**

Request you to kindly share essl biometric module & configuration documentation.
