### ISSUE TITLE
All the 1st time call takes longer time to respond in docker

### ISSUE THREAD

**Issue by BhuviTheDataGuy** [horilla-opensource/horilla#139]
I just cloned the repo and ran via docker-compose.

But every 1st call in the browser takes 2mins. Sometimes more, then all the sub options are loading fast.

Eg: under settings --> general took 1min, but every option inside it is loading fine.

The server has 8core and 16GB memory and its a new setup not having any active users.

**Comment by horilla-opensource** [comment]
Hi @BhuviTheDataGuy ,
We'll look into it and get back to you asap.

With Regards,
**Team Horilla**

**Comment by horilla-opensource** [comment]
Hi @BhuviTheDataGuy ,
We have checked the docker build in all platforms and we were not able to reproduce the issue you have mentioned.
Can you please check the logs and browser console to check for further details of the error and share with us if you find any lead on the issue ?

With Regards,
**Team Horilla**

**Comment by horilla-opensource** [comment]
Hi @BhuviTheDataGuy ,
Any updates?

With Regards,
**Team Horilla**

**Comment by BhuviTheDataGuy** [comment]
I don't know, I just started the server(after posting the issue, I stopped the VM), and now everything is working fine. But yeah we can close.
