### ISSUE TITLE
Biometric Integration Module 

### ISSUE THREAD

**Issue by sanjaysys** [horilla-opensource/horilla#143]
# Feature Request

## Description

Hi Team,

As per discussed with you please add module : essl biometric attendance integration .

share module file also.

**Comment by horilla-opensource** [comment]
Hi @sanjaysys ,
We have sent an email to you in the mail id that you have attached in the previous issue.
Please check and revert back under the thread.

With Regards,
**Team Horilla**

**Comment by sanjaysys** [comment]
Hi Team, 

Please Help getting some error when click on get employee data.
but showing connection is successfull not showing employee data.

When click on Test Button: Showing Connection test is successfull i haved checked IP ping request that is working fine.


Error: Failed to establish a connection. Please verify the accuracy of the IP Address and Port No. of the device.

**Comment by horilla-opensource** [comment]
Hi @sanjaysys ,
Can you please check the log after clicking the button and send us the log details to get a better understanding of the issue?

With Regards,
**Team Horilla**

**Comment by sanjaysys** [comment]
Hi Team,


I have attached Error Please check.



![Screenshot (18)](https://github.com/horilla-opensource/horilla/assets/159676415/295b658b-ed80-448e-9d05-83b81f35f6c0)
![Screenshot (19)](https://github.com/horilla-opensource/horilla/assets/159676415/e2bb5200-93aa-4fda-946f-b3e21156ec0e)
![Screenshot (21)](https://github.com/horilla-opensource/horilla/assets/159676415/8f96d38f-1664-419d-9ccf-0fb0de466376)

**Comment by mohdsaqib12** [comment]
We didn't find biometric feature. Please help us to get add biometric feature

**Comment by horilla-opensource** [comment]
Hi @sanjaysys ,
There was an issue in the code template and we have fixed it.
For an easy access, we have splitted the biometric system as a separate app and is now published in our biometric branch.
Please check that branch for the updated codebase.
Link: [Biometric Branch](https://github.com/horilla-opensource/horilla/tree/biometric)

With Regards,
**Team Horilla**

**Comment by horilla-opensource** [comment]
Hi @sanjaysys ,
Any updates?

With Regards,
**Team Horilla**

**Comment by sanjaysys** [comment]
> Hi @sanjaysys , Any updates?
> 
> With Regards, **Team Horilla**

Hi Team,

App is working fine device command working also but empoyee Data is not reflect in dashboard like In time or Out Time
while employee punch in or out to biometric.

**Comment by horilla-opensource** [comment]
Hi @sanjaysys ,
Is the data reflected in the attendance activity?

With Regards,
**Team Horilla**

**Comment by sanjaysys** [comment]
No Boss there is not showing.
![Att Record](https://github.com/horilla-opensource/horilla/assets/159676415/f3398393-4055-443b-aae8-131dfbcee791)

**Comment by sanjaysys** [comment]
No

**Comment by sanjaysys** [comment]
Which is Showing Blank only i am already checked every att section

**Comment by sanjaysys** [comment]
![error](https://github.com/horilla-opensource/horilla/assets/159676415/075934ef-d9fe-45fd-b93b-ba1c1bac4165)

Can you check this after run this command

**Comment by horilla-opensource** [comment]
> python3 manage.py compilemessages
> 
> Exexute Successfully but still not showing any attendance record i am already punch in 5 times.

The above command was not a fix for the attendance 😅. It was a command to load the terms for the breadcrumbs. Sorry for making you confused.

Can you please check the connection by clicking the Test button, and check if the connection is successful?

With Regards,
**Team Horilla**

**Comment by sanjaysys** [comment]
Yes Boss there is showing connection is successfull while clicking the Test button both devices. 
![Screenshot (24)](https://github.com/horilla-opensource/horilla/assets/159676415/085d0d7e-2a25-4df5-b245-76fb623c7215)
![Screenshot (25)](https://github.com/horilla-opensource/horilla/assets/159676415/873f0d2f-06eb-4ea5-9726-95f986d8977f)

**Comment by horilla-opensource** [comment]
Can you click on the schedule button and add the interval for syncing to 1 min and check?

**Comment by sanjaysys** [comment]
I am add own finger for the testing but i tried with every time puch in or out but not relfecting in dash board

**Comment by horilla-opensource** [comment]
Is the data not reflected still after changing the schedule to 1 min?

**Comment by sanjaysys** [comment]
Yees now it is working when changing schedule to 1 mint

**Comment by asis658** [comment]
Hi I am facing the exact same problem with biometric device. Everything seems fine but the attendance log isn't syncing from device to app. Scheduling also didn't fix this on my end.
