### ISSUE TITLE
Database Cleanup

### ISSUE THREAD

**Issue by mohdsaqib12** [horilla-opensource/horilla#145]
We want to reset / delete the dummy entry from the existing database. 

When delete any kind of entry. Then, database locked. Please help in to delete or truncate dummy entries.

**Comment by horilla-opensource** [comment]
Hi @mohdsaqib12 ,
If you want to start from a fresh database, either you can delete the current existing test database from the project directory and run the migrations command or else change the database name inside the settings.py file.
Go to horilla/settings.py file, inside which you'll find the configuration for the database like below: 
`DATABASES = {
        "default": {
            "ENGINE": env("DB_ENGINE", default="django.db.backends.sqlite3"),
            "NAME": env(
                "DB_NAME",
                default=os.path.join(
                    BASE_DIR,
                    "TestDB_Horilla1.sqlite3",
                ),
            ),
            "USER": env("DB_USER", default=""),
            "PASSWORD": env("DB_PASSWORD", default=""),
            "HOST": env("DB_HOST", default=""),
            "PORT": env("DB_PORT", default=""),
        }
    }`

Change the name of the database from TestDB_Horilla to your desire and run the migration command again to start with a fresh database.
PS: Please make sure that once after you create a fresh database, you create a horilla user using the createhorillauser command.

Please let us know, if you have any more queries.

With Regards,
**Team Horilla**

**Comment by mohdsaqib12** [comment]
Thank you so much Team Horilla. You guys amazing.

**Comment by horilla-opensource** [comment]
Thanks.
Can we please close this issue now?

With Regards,
**Team Horilla**
