### ISSUE TITLE
Can we Access over the LAN Network If we have already installed on VMware Machine Ubuntu local host: 127.0.0.1:8000

### ISSUE THREAD

**Issue by sanjaysys** [horilla-opensource/horilla#147]
# Feature Request

## Description

Hi Team,

Ques1: My question is i am already installed horiila on vmware machine in Ubuntu OS. that is working fine. but if we have need to access over the LAN network. so can we access or not. pls let me know me. if it is possible how can access over the local network please share documentation.

**Comment by uckons** [comment]
hi @horilla-opensource just try can't access from other PC in the same LAN using http://serverip:8000

**Comment by horilla-opensource** [comment]
Hi @uckons ,
Are you using the similar setup  of virtual machine?

With Regards,
**Team Horilla**

**Comment by uckons** [comment]
Hi @horilla-opensource yes using VM, and even i trying to access from other server in the same VM machine with same subnet still not working

**Comment by horilla-opensource** [comment]
Hi @uckons ,
Can you check with the firewall settings, if something is blocking the service ?

With Regards,
**Team Horilla**

**Comment by sanjaysys** [comment]
Same LAN but still is not working Please help i am trying ngrock also but is not working.

**Comment by Artapel** [comment]
Ive got the same issue on a new install. Seems that only local web access is allowed by default, I cannot find documentation to allow access from another IP on the same Subnet

**Comment by Artapel** [comment]
Ive disable the ubuntu firewall (ufw), i cann ssh into ubuntu just fine, just cannot browse to HTTP://ipaddress:8000 from another machine.

ERR_CONNECTION_REFUSED

**Comment by horilla-opensource** [comment]
Hi @Artapel ,
We haven't add any settings to allow only the local web access by default.
Our demo instance (demo.horilla.com) is hosted on an aws ubuntu server with basic configurations for django.
Can you please share with us the settings.py file contents (removing the private credentials) and also how you have hosted the service?
Also can you please check if the port 8000 is opened in the server and also the status of the service?

With Regards,
**Team Horilla**

**Comment by jomausiu** [comment]
Run the server with the following command
- Add 0:8000 to provide external access via LAN

python manage.py runserver 0:8000
