### ISSUE TITLE
Documentation Required for host on aws ubuntu server.

### ISSUE THREAD

**Issue by mohdsaqib12** [horilla-opensource/horilla#148]
Dear Team,

If you guys have any documentation for host this HRMS into AWS ubuntu server. Please share or tell us is there any specific requirement to host this hrms on AWS.

Please reply!

**Comment by horilla-opensource** [comment]
Hi @mohdsaqib12 ,
Currently we don't have the doc for hosting Horilla in AWS server.
We'll share a doc for the same asap.

With Regards,
**Team Horilla**

**Comment by mohdsaqib12** [comment]
Thanks! Please share asap. We are ready to launch HRMS. 

Horilla HRMS is amazing product! 

Well done team Horilla.

**Comment by BhuviTheDataGuy** [comment]
Its well documented :) 

1. [installation](https://www.horilla.com/docs/installation/#ubuntu)
2. [DB Setup](https://www.horilla.com/docs/database-setup/#postgressql) 
3. [Bonus - One click install](https://www.horilla.com/docs/installation-using-shell-script/#ubuntu-macOS)

**Comment by horilla-opensource** [comment]
Hi @mohdsaqib12 ,
Also please refer to this blog for the detailed way to have it  host Horilla in AWS.
[How to Host Horilla HRMS Software Using Gunicorn+Nginx in Production?](https://www.horilla.com/blogs/how-to-host-horilla-hrms-software-using-gunicornnginx-in-production/)

With Regards,
**Team Horilla**

**Comment by horilla-opensource** [comment]
Hi @mohdsaqib12 ,
Closing the issue as the doc for hosting has been provided.

With Regards,
**Team Horilla**
