### ISSUE TITLE
Migration files need to upload in Master horilla Folder

### ISSUE THREAD

**Issue by sanjaysys** [horilla-opensource/horilla#150]
# Bug Report

## Description

Hi Team,

This is inform you that please upload migration file on onboarding folder. some of the function is not wokring please once check.

Resolve the issue.

Request you to please check once migration file on every module folder. Basically 

migration file not available on Horilla-Biometric Onboarding folder i have add manually .

**Comment by horilla-opensource** [comment]
Hi @sanjaysys ,
We don't usually add the migrations file for the apps in the github. We added the migrations folder inside the gitignore, so the local migrations files will not be pushed to the github repo.
Users starting with fresh database usually will have issues if we add the migrations folder in the codebase. For the test database we usually update the test database once there is a change in the models.

Also the migrations folder will automatically be generated in the app folder once you run the makemigrations command.

With Regards,
**Team Horilla**

**Comment by sanjaysys** [comment]
okky sir thanku so much

**Comment by sanjaysys** [comment]
okkay so now my biometric app working fine nd i have upload one user that is upload successfully. but attendance data is not reflect on dashboard my att record

**Comment by horilla-opensource** [comment]
Hi @sanjaysys ,
Did you check the connection the if its successful using the test connection option?
If the test is successful, either you can enable live capture or add an interval for capturing the attendance from the machine using the schedule option which is available in the biometric devices card view.

With Regards,

**Comment by horilla-opensource** [comment]
[[IMP] ONBOARDING: Add missing migrations folder and __init__.py file](https://github.com/horilla-opensource/horilla/commit/4cc3d4e3e9b8cbd7283b3f6754df451c40209532)
