### ISSUE TITLE
nginx reverse proxy

### ISSUE THREAD

**Issue by uckons** [horilla-opensource/horilla#151]
HI All,
do you know ho to setup https reverse proxy using nginx, i been done setup only login page , when try to login i got error :

Reason given for failure:

    Origin checking failed - https://hrms.adikarya.biz.id does not match any trusted origins.
    
In general, this can occur when there is a genuine Cross Site Request Forgery, or when Django’s CSRF mechanism has not been used correctly. For POST forms, you need to ensure:

Your browser is accepting cookies.
The view function passes a request to the template’s render method.
In the template, there is a {% csrf_token %} template tag inside each POST form that targets an internal URL.
If you are not using CsrfViewMiddleware, then you must use csrf_protect on any views that use the csrf_token template tag, as well as those that accept the POST data.
The form has a valid CSRF token. After logging in in another browser tab or hitting the back button after a login, you may need to reload the page with the form, because the token is rotated after a login.
You’re seeing the help section of this page because you have DEBUG = True in your Django settings file. Change that to False, and only the initial error message will be displayed.

You can customize this page using the CSRF_FAILURE_VIEW setting.

**Comment by uckons** [comment]
hi @horilla-opensource amazing it works now

**Comment by horilla-opensource** [comment]
Hi @uckons ,
Can we please close this issue?

With Regards,
**Team Horilla**

**Comment by uckons** [comment]
Sure @horilla-opensource closed this issue

**Comment by uckons** [comment]
Awesome

**Comment by unexcitement** [comment]
I am having this same issue however putting my domain in CSRF_TRUSTED_ORIGINS didn't make a difference. I am running it with docker and have tried using the env.dist and I have also tried changing it directly in settings.py

**Comment by wole001** [comment]
Hello,

Please as of last year, this fix worked. But recently even configuring the CSRF_TRUSTED_ORIGINS, it still returns the error. 
Dont know if it has to do with the Django version update 

![Image](https://github.com/user-attachments/assets/b3654b16-f267-4310-923e-31fa1a36b53d)

**Comment by wole001** [comment]
In addition, I have tried tweaking my nginx config but no luck as that 

![Image](https://github.com/user-attachments/assets/7f8179ed-58e4-4998-8a50-14a874051fa8)

It still returns the error

![Image](https://github.com/user-attachments/assets/9e6d8e44-4384-45a5-ae83-81b6cc952ec5)

![Image](https://github.com/user-attachments/assets/ebaa92f0-8eb5-4a3a-b49e-7941437b540c)
