### ISSUE TITLE
Company logo 404

### ISSUE THREAD

**Issue by BhuviTheDataGuy** [horilla-opensource/horilla#154]
After the installation, created the company and uploaded the logo. 

Once the server restarted, then the logo in missing. 
![image](https://github.com/horilla-opensource/horilla/assets/47310439/6278a4f2-4926-401a-88f1-4df6959b3189)

Logs:
```
server-1  | Not Found: /media/base/icon/shellkode-logo-png.png
server-1  | Not Found: /templates/navbar.html
server-1  | Not Found: /templates/sidebar.html
```
If I create a new company and upload the same logo, then it works(it has the same name) until the next restart.

**Comment by horilla-opensource** [comment]
Hi @BhuviTheDataGuy ,
Can you check after uploading the icon in a new session?
Upload the icon, and in a new session (maybe in an incognito tab) login and check if the issue persists.
Need to confirm if it is an issue with sesssion somehow the media files are not loaded.

With Regards,
**Team Horilla**

**Comment by BhuviTheDataGuy** [comment]
May be session issues. Now its fine. Im running in native installation mode(not on the docker)

**Comment by horilla-opensource** [comment]
We'll check into it for what caused the issue. 👍🏻
