### ISSUE TITLE
Recruitments: Kanban board not sortable

### ISSUE THREAD

**Issue by borishinzer** [horilla-opensource/horilla#16]
**Describe the bug**
The steps in the recruiting kanban board can't be sorted

**To Reproduce**
1. Go to https://horillaurl/recruitment/pipeline?view=card
2. Try to sort by drag'n'drop 
3. Error: Not working (tested on Firefox)

**Expected behavior**
Sorting working

**Screenshots**
<img width="1073" alt="Bildschirmfoto 2023-07-25 um 21 31 43" src="https://github.com/horilla-opensource/horilla/assets/10340538/b0e88dc5-261e-4787-aa33-6391a369caa9">

**Desktop (please complete the following information):**
MacOS
Firefox
115.0.2 
[](url)

**Comment by borishinzer** [comment]
Drag'n'Drop was expected at the three dots. It seems that the Bubble with the amount of persons in that column could be used instead. Unfortunately when you then decide to rename a column again. The kanban board gets mixed again.

**Comment by borishinzer** [comment]
In list view sorting is not working at all

**Comment by horilla-opensource** [comment]
Hi @borishinzer ,
Thanks for taking your time and pointing out the issue in our software.
We  have analysed the bug and fixed it.
You can find the latest updated code from the master branch. (https://github.com/horilla-opensource/horilla/commit/d85bd5e5e577d119438c61eb34ee91e6104d4c6c)
Users can now update the sequence of the stages and candidates by drag and drop.
We have tested the same across different browsers and OS.
Feel free to raise any issues or you have any suggestions.
With Regards,
**Team Horilla**

**Comment by borishinzer** [comment]
Thanks a lot for the prompt fix.
