### ISSUE TITLE
PaySlip Format Changes

### ISSUE THREAD

**Issue by sanjaysys** [horilla-opensource/horilla#162]
# Feature Request

## Description

Hi Team,

Can we change or modify Payslip format or add heading, and company logo also.

If its it possible request you to please share me the same.

**Comment by horilla-opensource** [comment]
Hi @sanjaysys ,
For updating the format of the payslip, you'll have to alter its html template.
If its just with the adding of company logo and name, we'll add it for you.

With Regards,
**Team Horilla**
