### ISSUE TITLE
Password is not able to received when create a new employee

### ISSUE THREAD

**Issue by sanjaysys** [horilla-opensource/horilla#163]
# Bug Report

## Description

Hi Team,

We have facing one rare issue while creating new employee his password is not received on mail.
I know as well his bydefault password is mobile not if why is received his on mail for future reference.

can you please look into this.

**Comment by horilla-opensource** [comment]
Hi @sanjaysys ,
Sorry, we didn't understand the issue correctly.
Do you want to send the password setting direction for the employees on creation?

With Regards,
**Team Horilla**

**Comment by sanjaysys** [comment]
User Password is not receiving on his email address. when we add new employee

**Comment by BhuviTheDataGuy** [comment]
Thats fine, I was thinking once the user is created they will be notified by email. 

But that's fine. Now I understood its the design.
