### ISSUE TITLE
Leave type is not loaded

### ISSUE THREAD

**Issue by BhuviTheDataGuy** [horilla-opensource/horilla#166]
I have created 6 different leave types, but it's not loading while applying for leave. 

![image](https://github.com/horilla-opensource/horilla/assets/47310439/e0da0978-9a71-44db-83c9-d9872360b4f7)

**Comment by horilla-opensource** [comment]
Hi @BhuviTheDataGuy ,
Did you allocate the leave type for the employee?

With Regards,
**Team Horilla**

**Comment by BhuviTheDataGuy** [comment]
Im the admin user, the employee name wont be visible.

![image](https://github.com/horilla-opensource/horilla/assets/47310439/8fd78d72-95d2-4b38-a26a-a896a0c0199e)

**Comment by horilla-opensource** [comment]
Did you click on My Leave Requests or Leave Requests?
The My Leave Request menu is specifically for the current logged in user, so you won't be able to select the users in that and it is meant for normal users. (So if you don't see a leave type in that means, you are not allocated any leave type. Please check if the current logged in user has a leave type assigned)
The Leave Request menu is for the admin, where the admin will be able to see all requests and also create requests for other users. There you'll be able to select other users also.

Please let me know if you have any doubts on this.

With Regards,
**Team Horilla**

**Comment by BhuviTheDataGuy** [comment]
Understood, first, we need to allocate the leave to the employee, then they can pick that card while applying for leave. It worked. 

Is there any way the admin can assign leave type to all employees(instead of selecting the users one by one)

**Comment by horilla-opensource** [comment]
Yes, you can assign leave types to all employees.
Go to leave types and select any one leave type. When you click on a leave type, you'll find a popup including the leave type details, where you'll find a assign button.
Click on the assign button, and you'll find an option to select multiple employees and also able to filter and select employees based on different conditions also.
Please refer the below video:

https://github.com/horilla-opensource/horilla/assets/131998600/b84b100b-cc7a-492a-ba78-fdfcea86bb8e

 
With Regards,
**Team Horilla**

**Comment by BhuviTheDataGuy** [comment]
Awesome thanks,
