### ISSUE TITLE
How to Change Biometric User ID

### ISSUE THREAD

**Issue by sanjaysys** [horilla-opensource/horilla#171]
# Feature Request

Hi Team,

I want know that can we change Biometric user ID that is starting from 1000 number if we add new employee his user ID is starting number from 1015 so we want change user id that is every time starting from GM001 it is possible or not.
or change anything from database files

**Comment by horilla-opensource** [comment]
Hi @sanjaysys ,
To change the sequence number starting from 1000, you can update it by making small change in code.
Inside the biometric app > views.py, you'll find a line : `user_id = 1000`
Update the value from 1000 to 1015 and rerun the server.
Also about the characters as prefix in the id, we are looking into it as sometimes there were issues when we add characters to the badge id in the ZK machines.
We'll provide an update on that asap.

With Regards,
**Team Horilla**

**Comment by sanjaysys** [comment]
Sir I already tested the same but i need to add some character like GM1001.

user id number is working fine when it change something different but i need starting from GM1001

**Comment by CybroOdooDev** [comment]
We are looking into that.
But sometimes there comes an issue with the compatibility of characters within the ZK machines.
We'll update you with a solution to it.

With Regards,
**Team Horilla**

**Comment by horilla-opensource** [comment]
We are looking into that.
But sometimes there comes an issue with the compatibility of characters within the ZK machines.
We'll update you with a solution to it.

With Regards,
**Team Horilla**

**Comment by sanjaysys** [comment]
Okkay Thanks for quick response i have 1 query.

**Comment by CybroOdooDev** [comment]
Sure, go ahead.

**Comment by horilla-opensource** [comment]
Sure, go ahead.

**Comment by sanjaysys** [comment]
Please give me 5 mintes i will show you

**Comment by sanjaysys** [comment]
![Payslip Format](https://github.com/horilla-opensource/horilla/assets/159676415/3aab4765-16b0-4a11-b0b4-71e96266ea7b)


Basically I want to change some table with sequence but while creating pdf payment slip default payment slip shows different type.

So you are requested to please change the format as per my requested format while creating the PDF payment slip.

You can only make allowances and deductions in the same line

Like that 
Allowances | Amount | Deductions | Amount
Basic              00           PF
HRA               00           ESI
Other                            TDS
Total Gross Pay            Total Deductions:
Net Pay


Please help with i try to change but facing lot off error.

**Comment by sanjaysys** [comment]
Thanks boss

I am already working on it, if the work is done from my side then I will share you code also.

**Comment by sanjaysys** [comment]
Its Completed or Not

**Comment by horilla-opensource** [comment]
Not completed.
Will share the update.

**Comment by sanjaysys** [comment]
Any Update

**Comment by horilla-opensource** [comment]
Hi @sanjaysys ,
Sorry for the delay.
The payslip view is completed based on the screenshot that you have given. But we are facing an issue while downloading the payslip. On downloading, the design gets changed. The allowances and deduction table come as two different row rather being in a single row. 
Our design team is working on the fix for it.
We'll share with you the code once that's fixed.

With Regards,

**Comment by sanjaysys** [comment]
okky boss

**Comment by horilla-opensource** [comment]
Hi @sanjaysys ,
Sorry for the delay in the solution. We had face some issue in the design conversion to pdf.
Download the new html file from this link : [individual_pdf.html](https://drive.google.com/file/d/1tSBdcx1gySF_FSf9NXtFSpFBhsBsEc4u/view?usp=sharing)
Replace the individual_pdf.html (payroll/templates/payroll/payslip/individual_pdf.html) with the attached individual_pdf.html in this comment.
Also we have a doubt with the two fields which we have hardcoded into it. The fields are _Monthly CTS_ and _Monthly Payable_

Please let us know if you face any issues.



With Regards,
**Team Horilla**

**Comment by sanjaysys** [comment]
Thanku Buddy

**Comment by sanjaysys** [comment]
![image](https://github.com/horilla-opensource/horilla/assets/159676415/932c2a22-ec0f-4e6d-9ddd-5eadb2969f42)



Hi Team,

allowances not showing on payslip when download salary slip.


already added HRA, Conveyance Allowance,  
![image](https://github.com/horilla-opensource/horilla/assets/159676415/9ad3a9ff-cbc5-4421-9ac7-b575cc89447d)


I guess its issue from allowances title or anything else. Pls help

**Comment by horilla-opensource** [comment]
Hi @sanjaysys ,
Please close this issue and open a new issue with new title (you can mention this issue in that issue) as the title of the issue is completely different from the points that we are discussing.
It'll be better if a new discussion is opened for the same.

With Regards,
**Team Horilla**

**Comment by sanjaysys** [comment]
Okkay Thanks
