### ISSUE TITLE
Exporting Attendance data error

### ISSUE THREAD

**Issue by BhuviTheDataGuy** [horilla-opensource/horilla#174]
While exporting the attendance data, we are getting the error.

Fix 
```
pip install --upgrade jinja2
```
![image](https://github.com/horilla-opensource/horilla/assets/47310439/4e5795c4-04be-4f42-a733-a9a7c9dfc378)

**Comment by horilla-opensource** [comment]
Hi @BhuviTheDataGuy ,
The requirements file is adjusted with the required jinja2 versions.
Hence closing the issue.
Thanks.

With Regards,
**Team Horilla**
