### ISSUE TITLE
Payslip Download Error  UnboundLocalError at /payroll/payslip-pdf/7

### ISSUE THREAD

**Issue by sanjaysys** [horilla-opensource/horilla#176]
# Bug Report

Hi Team,

When Employee download his payslip from dashboard showing this error.

Kindly look into this. I have attached screen shot also.

![Screenshot 2024-05-06 124531](https://github.com/horilla-opensource/horilla/assets/159676415/8aba9ebd-b102-4d7c-9bf3-c0f6b7fda424)

**Comment by horilla-opensource** [comment]
Hi @sanjaysys ,
The solution for the issue is added in the latest commit.
Please check.

With Regards,
**Team Horilla**

**Comment by sanjaysys** [comment]
Okkay Can you please guid how to push from old files to new commit
