### ISSUE TITLE
Checkin time reset every refresh or navigate to another menu

### ISSUE THREAD

**Issue by BhuviTheDataGuy** [horilla-opensource/horilla#178]
After the new version upgrade, the check-in time resets every time the page get loaded.

![horilla2](https://github.com/horilla-opensource/horilla/assets/47310439/c3450857-0f53-4b73-9300-aca750cd66fd)

**Comment by horilla-opensource** [comment]
Can you check by checking out and checking in again?
I think its an issue with session.

**Comment by BhuviTheDataGuy** [comment]
Yes, working
