### ISSUE TITLE
Remove leave feature 

### ISSUE THREAD

**Issue by MagloireKITIO** [horilla-opensource/horilla#179]
what if I don't want the leave feature and want to disable it without error?  becquse i have this error evrey time django.db.utils.OperationalError: no such column: leave_leavetype.is_compensatory_leave

**Comment by horilla-opensource** [comment]
Are you having the issue with the test database provided or with a new fresh database?!

**Comment by horilla-opensource** [comment]
Hi @MagloireKITIO ,
Can you please check with this comment: https://github.com/horilla-opensource/horilla/issues/173#issuecomment-2102491275

With Regards,
**Team Horilla**
