### ISSUE TITLE
Bulk approval for attendance request

### ISSUE THREAD

**Issue by BhuviTheDataGuy** [horilla-opensource/horilla#182]
Is there any way to bulk approval of attendance requests?
![image](https://github.com/horilla-opensource/horilla/assets/47310439/d7b38616-9d8d-43d5-94a8-d748221c4391)

**Comment by horilla-opensource** [comment]
Hi @BhuviTheDataGuy ,
The feature for bulk approval of attendance requests is added in the latest commits.
Please check and let us know if you have any more concerns related to it.

With Regards,
