### ISSUE TITLE
Announcement - Character length issue

### ISSUE THREAD

**Issue by BhuviTheDataGuy** [horilla-opensource/horilla#185]
The announcement title seems to be support for 469 characters(from the error message), but its not working for 10 chars also. 

![image](https://github.com/horilla-opensource/horilla/assets/47310439/c20dbe9e-f9e6-455a-8d97-2ae95d2a01ca)

**Comment by horilla-opensource** [comment]
Hi @BhuviTheDataGuy ,
The solution for the issue is updated.
Please check and let us know .

With Regards,
**Team Horilla**

**Comment by horilla-opensource** [comment]
Hi @BhuviTheDataGuy ,
Any updates on the solution we have provided?
Were you able to test it out ?

With Regards,
**Team Horilla**

**Comment by BhuviTheDataGuy** [comment]
I’ll test it and share the updates
