### ISSUE TITLE
Automatic sorting of resumes.  shortlist

### ISSUE THREAD

**Issue by MagloireKITIO** [horilla-opensource/horilla#188]
One of the features that could add real value is the ability to automatically sort resumes by keyword. Do you have any idea how this could be implemented?

**Comment by horilla-opensource** [comment]
Hi @MagloireKITIO ,
The team is having it on the pipeline as a feature to be implemented.
We are planning to add an automatic resume parser which will list out the data from the resume and add it to the candidate profile automatically without needing to fill in manually.
Will let you know once that's been done.

With Regards,
**Team Horilla**

**Comment by MagloireKITIO** [comment]
Goooooooood, I'm still waiting 

thank you team

**Comment by horilla-opensource** [comment]
Hi @MagloireKITIO ,
The resume shortlisting is now added in the master code base.
<img width="1470" alt="Screenshot 2024-07-09 at 2 27 35 PM" src="https://github.com/horilla-opensource/horilla/assets/131998600/66934471-3861-41fe-a6d2-74b37645cdff">

With Regards,
**Team Horilla**

**Comment by MagloireKITIO** [comment]
Very gooddddd news  . thank you

**Comment by MagloireKITIO** [comment]
how it works ?

**Comment by horilla-opensource** [comment]
**Resume Shortlisting**

1. In the recruitment pipeline, click on the three dots on the tab heads.
2. Select "Resume Shortlisting" from the dropdown menu.
3. Click on the "+" button to add resumes.
4. You can add multiple files at once.
5. After adding the resumes, the system will automatically calculate the scores for each resume.
6. The scoring is based on the number of skills present in each resume that match the required skills for the recruitment.
7. Resumes will be displayed in descending order of their scores.
8. Click on the "Create Candidate" button to be redirected to the candidate creation form.
9. The form will be auto-filled with data extracted from the resume.
10. Verify the accuracy of the information in the fields by checking the preview of the resume on the right side.
11. Submit the form to create the candidate.
12. To create another candidate, return to the previous tab.
13. Click on the "Create Candidate" button again to repeat the process.


**Note**
Some types of PDFs, such as image PDFs or scanned PDFs, cannot be read by the system.
These resumes will be marked as "Need Verification" in the score column.

With Regards,
**Team Horilla**

**Comment by MagloireKITIO** [comment]
![Capture d’écran 2024-07-15 082332](https://github.com/user-attachments/assets/b37518ed-10b7-4a1d-8e24-53dcc81a4255)
<img width="852" alt="image" src="https://github.com/user-attachments/assets/e65e810d-8f4f-436c-b9ff-554342df856f">

I can't find the functionality and even when I want to change the candidate's status to the next step, nothing happens.

**Comment by horilla-opensource** [comment]
Did you pull the latest code?

**Comment by MagloireKITIO** [comment]
yes

**Comment by horilla-opensource** [comment]
Hi @MagloireKITIO ,
Were you able to test it out ?

With Regards,
**Team Horilla**

**Comment by MagloireKITIO** [comment]
yes is good now, thank you

**Comment by horilla-opensource** [comment]
Hi @MagloireKITIO ,
Can we close this issue now ?

With Regards,
**Team Horilla**
