### ISSUE TITLE
"Based on" field missing from create allowance form

### ISSUE THREAD

**Issue by anoninthekop** [horilla-opensource/horilla#193]
# Bug Report

## Description

In the documentation it mentions that there is a "based on" field which includes various options such as “Basic Pay,” “Attendance,” “Shift,” “Overtime,” and “Work Type” to define the criteria for determining the allowance amount but I cannot find it when running Horilla in my system.

![how-to-create-payroll-allowances-in-horilla-payroll-management-software-5](https://github.com/horilla-opensource/horilla/assets/41584769/d66c31e7-c305-459f-abca-9bef9638f4ed)

Here is how it looks on my pc:

![Horilla allowance](https://github.com/horilla-opensource/horilla/assets/41584769/ebf57ea9-21be-4277-8f61-70cf2ef1d9eb)

In the current version cannot find any way to make an allowance or deductions based on the overtime hours worked

**Comment by horilla-opensource** [comment]
Hi @anoninthekop ,
Can you check out by toggling the boolean field for _is fixed_ field?

With Regards,
**Team Horilla**

**Comment by anoninthekop** [comment]
Thanks @horilla-opensource turning _is fixed_ off shows the _based on_ . Another query I have is is there currently anyway to create an automatic deduction based on absent days or late minutes.

For example, an implementation could be to add options such as absent hours or late hours to the _based on_ field. I'm thinking about implementing it myself but I wanted to check with you first.

**Comment by horilla-opensource** [comment]
Hi @anoninthekop ,
We have a one time deduction for the late come or absent days which is now added manually. The team has been having discussion on the automatic deduction, but there are some other features in the timeline with which the automatic deduction concept is being delayed.
You are try it out from yourself and make a PR for the same. We'll be glad to add it to our codebase and will be much appreciated for your work.

With Regards,
**Team Horilla**
