### ISSUE TITLE
Payroll - Employee List not shown up in payroll form

### ISSUE THREAD

**Issue by mohdsaqib12** [horilla-opensource/horilla#211]
Once, we are going to create employee pay slip. Employees not shown up in dropdown list.

**Comment by horilla-opensource** [comment]
Hi @mohdsaqib12 ,
The payslip will be generated only for that employees who has an active contract.
Please check for the employees if their contracts are active.

With Regards,
**Team Horilla**

**Comment by mohdsaqib12** [comment]
@horilla-opensource Got it. Thanks for the help!

**Comment by horilla-opensource** [comment]
Can we close this issue?

**Comment by mohdsaqib12** [comment]
Yes, please!

Thank you
