### ISSUE TITLE
Hide other features according to settings

### ISSUE THREAD

**Issue by XConradX** [horilla-opensource/horilla#230]
# Feature Request

## Description

_[Can we hide other features like payroll and etc?.]_

## Use Case

_[I would like to just grant access to specific group.]_

## Proposed Solution

_[Provide your ideas or suggestions on how this feature could be implemented. This is optional.]_

## Benefits

_[Highlight the benefits and value this feature would bring to users or the project as a whole.]_

## Additional Information

_[Any other relevant information, details, or examples related to the feature request.]_

## Labels

_[If your project uses labels, suggest any labels that might apply to this feature request, such as 'enhancement', 'feature request', etc.]_

## Priority

_[Specify the priority level for this feature request, such as 'high', 'medium', 'low', etc.]_

## Assignees

_[If you want to suggest an assignee or tag a specific person to consider this feature request, mention their GitHub username here.]_

## Related Issues

_[If there are any related issues or pull requests, mention them here. This is optional.]_

**Note:** _Before submitting a new feature request, please search through existing issues to ensure that the feature hasn't been requested already. Provide clear and concise information to help the maintainers understand the proposed feature and its potential impact._

**Comment by horilla-opensource** [comment]
Hi @XConradX ,
Which are the modules that you do not require in the system?

With Regards,
**Team Horilla**

**Comment by XConradX** [comment]
Thanks Team Horilla for taking time with my query. 
I actually need all the modules but I would like to gradually introduce it feature by feature. i.e 
In example I want to hide first the attendance, pms and payroll feature and the rest are open. 
After three months, I will then activate the rest of the features. Is that possible?

**Comment by horilla-opensource** [comment]
Hi @XConradX ,
One thing that we can do now is hide the menu's from the sidebar and settings as we cannot completely remove the modules from the system. The unnecessary module's menus can be hidden for the time being ans when you want them, they can be made visible.
The above can be achieved by commenting the corresponding elements from the code. 
For hiding the elements from the sidebar, there is a sidebar.py file in each module, in which you can comment out the unnecessary menus.

With Regards,
**Team Horilla**

**Comment by XConradX** [comment]
Hi Thanks! its now working for both instructions

**Comment by horilla-opensource** [comment]
Can we close this issue now?

With Regards,
**Team Horilla**

**Comment by XConradX** [comment]
yes please, thank you again Team Horilla
