### ISSUE TITLE
add a column. "used days" in Leave app>Assigned Leave

### ISSUE THREAD

**Issue by XConradX** [horilla-opensource/horilla#232]
As an HR, how do I add a column in Assigned Leave. "used days or number of days taken" in assigned leave report?

<img width="1381" alt="image" src="https://github.com/horilla-opensource/horilla/assets/174324408/1c5386e2-3ef5-438f-8c15-7911864fd819">

**Comment by horilla-opensource** [comment]
Hi @XConradX ,
The team is adding that to the view. Will update you once done.

With Regards,
**Team Horilla**

**Comment by horilla-opensource** [comment]
Hi @XConradX ,
The column is added in the table view in the latest commit.
Please check.

With Regards,
**Team Horilla**

**Comment by XConradX** [comment]
I can now see the column. many thanks!
