### ISSUE TITLE
Job role to multiple job position dosent work

### ISSUE THREAD

**Issue by zgurea1** [horilla-opensource/horilla#236]
# Bug Report

## Description

Hello guys, i tried to add one Job Role to multiple Job Position and its saying that Job position already exists.
I don't think is correctly working because different Job Positions can have the same Job Role.
Is there a workaround it?

## Steps to Reproduce

1. Create 2 Job Position 
2. Create a Job Role in first Job Position 
3. Add the Job Role to the second Job Position

## Expected Behavior

To add this Job Role

## Actual Behavior

Job Position with this Job position already exists.

## Environment
The latest version.

## Possible Solution
To make it possible to add a job role to multiple job positions.

**Comment by horilla-opensource** [comment]
Hi @zgurea1 ,
The fix for the issue is added in the latest commit.
Please check and let us know if you face any more issues.

With Regards,
**Team Horilla**

**Comment by zgurea1** [comment]
@horilla-opensource Hi, the same problem with multiple departments have the same job position: Example: Department Marketing - Position Manager, Department IT - Position Manager.
Is giving the same error: Job Position with this Job position already exists.

**Comment by zgurea1** [comment]
@horilla-opensource for Job role is working grate, i will make a new issue for job position.
THX!
