### ISSUE TITLE
its accessible only on localhost address

### ISSUE THREAD

**Issue by wasimkhan2024** [horilla-opensource/horilla#239]
I've installed the software and its accessible on localhost address that is localhost:8000 but when i try to the same software on LAN from another PC using IP address with the said port, it's not accessible. would you plz help me out on this?

**Comment by horilla-opensource** [comment]
Hi @wasimkhan2024 ,
You should be able to access the software in the same network using the ipv4 address of the system in which Horilla is hosted.
Please confirm which page you are getting when you try to access the system? Are you getting the general _Page not found_ or any page related to Horilla ?
If its not accessible, please confirm there is no firewall blocking it.

With Regards,
**Team Horilla**

**Comment by wasimkhan2024** [comment]
i am using the IPv4 address of the same network, even its IP is pingable. Lets say, horilla is installed on a system having IP address 192.168.1.100/24 and i m trying to access the software from a system having IP address 192.168.1.101/24 using URL http://192.168.1.100:8000 in a browser but it shows can't reach to the page.

**Comment by horilla-opensource** [comment]
Hi @wasimkhan2024 ,
We don't have a restriction within Horilla, which restricts it being distributed within the same network.
Our team tested it from our network and its working fine.
Can you confirm with the firewall settings or if there is any protocols enabled which is stopping the service from being distributed?

With Regards,
**Team Horilla**

**Comment by wasimkhan2024** [comment]
thanks for your response, On Lan that system is fully accessible expect horilla....dont you think that port is being blocked by Python?

**Comment by horilla-opensource** [comment]
No, there's nothing like that in the code base which blocks an outgoing request to a port.
Can you check with the browser console of the system in which you are trying to access Horilla ?

**Comment by wasimkhan2024** [comment]
the system on which horilla is installed, when i enable xampp server with port 81 then its accessible on LAN but on the same system when i disable xamp server and run python for accessing horilla from the same LAN, its not working...i dont know where the problem is, let me clarify that both systems are windows 10 based. please your guidance is required to deploy the solution as soon as possible

**Comment by wasimkhan2024** [comment]
i found the solution here: https://stackoverflow.com/questions/5768797/manage-py-runserver

**Comment by horilla-opensource** [comment]
Hi @wasimkhan2024 ,
Glad to hear that your issue is solved.

With Regards,
**Team Horilla**
