### ISSUE TITLE
Bug when exports Leave 

### ISSUE THREAD

**Issue by zgurea1** [horilla-opensource/horilla#240]
# Bug Report

## Description
Hi, tried to download list of leaves and i got error. 
I will try to add this package to entrypoint.sh to is if its fix the issue.

## Steps to Reproduce

1. Go to Assigned Leave 
2.  Click Action -> Export

## Expected Behavior

Export all leaves in excel format

## Actual Behavior
This is the error:

ImportError at /leave/assigned-leaves-info-export

Missing optional dependency 'Jinja2'. DataFrame.style requires jinja2. Use pip or conda to install Jinja2.

## Environment

Latest version.

## Possible Solution

Maby to install pip or conda to install Jinja2.

**Comment by horilla-opensource** [comment]
Hi @zgurea1 ,
It's because of a missing dependency in the requirements.
Please install Jinja2 package and try again.
```
pip3 install Jinja2
```


With Regards,
**Team Horilla**

**Comment by zgurea1** [comment]
@horilla-opensource thx, have a great day.
