### ISSUE TITLE
Duplicate in settings.py

### ISSUE THREAD

**Issue by gehasia** [horilla-opensource/horilla#243]
https://github.com/horilla-opensource/horilla/blob/c719c91a801aad39e0eec563c9f15cd02f4182b8/horilla/settings.py#L205

The LANGUAGE_CODE = "en-us" is still duplicated in settings.py

lines 205 AND 223

That can lead to incorrect behavior if user set it on line 205 only (overridden on line 223)

**Comment by horilla-opensource** [comment]
Hi @gehasia ,
Removed the duplicate entry.
Thanks for pointing it out.

With Regards,
**Team Horilla**
