### ISSUE TITLE
Job Position to multiple departmets dosent work

### ISSUE THREAD

**Issue by zgurea1** [horilla-opensource/horilla#246]
# Bug Report

## Description

Hi guys, i tried to make multiple departments, after  that, i created the same job position for multiple departments.

## Steps to Reproduce

1. Create 2 departments
2. Create 1 job position for the first department (Example: Manager -> Sales Dep)
3. Create the same job position for different department (Example: Manager -> HR Dep)

## Expected Behavior

To create the same job position for multiple departments.

## Actual Behavior

Job Position with this Job position already exists.

## Environment
The latest version.

## Possible Solution

_[If you have any ideas or suggestions on how to fix the issue, feel free to provide them here. This is optional.]_

**Comment by horilla-opensource** [comment]
Hi @zgurea1 ,
The solution is updated in the latest commit.
Please check and let us know if you face any issues.

With Regards,
**Team Horilla**

**Comment by zgurea1** [comment]
@horilla-opensource hi, its working, but if you dublicate the same job position in one department it not showing error.
![image](https://github.com/horilla-opensource/horilla/assets/60965273/502f56ed-0b68-44aa-911c-d3871c06cada)

DETAIL:  Key (job_position)=(Specialist principal) already exists.

Internal Server Error: /settings/job-position-creation/
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "base_jobposition_job_position_key"
DETAIL:  Key (job_position)=(Specialist principal) already exists.

**Comment by horilla-opensource** [comment]
Hi @zgurea1 ,
Can you try by creating another record with new data and confirm whether its working?

With Regards,
**Team Horilla**

**Comment by sharukhkhan234** [comment]
@horilla-opensource 
I mentioned to you the same error, also I have sent ss of the mistakes with the editable code that you had provided

**Comment by horilla-opensource** [comment]
Hi @sharukhkhan234 ,
Were you able to work around with it?

With Regards,
**Team Horilla**
