### ISSUE TITLE
Create a new employee results in error message

### ISSUE THREAD

**Issue by borishinzer** [horilla-opensource/horilla#26]
**Describe the bug**
Create a new employee results in error message. 
Please see screenshot for details.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Firefox
 - Version: 116
![Bildschirmfoto 2023-08-10 um 17 22 05](https://github.com/horilla-opensource/horilla/assets/10340538/57533caa-10b3-461b-8e96-6972e8f309cc)

**Comment by horilla-opensource** [comment]
Hi @borishinzer,
The issue is because of a major change we made.
Either you can use our latest demo database or you can provide the database to us, we'll fix it and send it you.
Sorry for the inconvenience caused.
With Regards,
**Team Horilla**

**Comment by horilla-opensource** [comment]
Sure, we get your concern.
We'll soon provide the steps to fix the database issue.
With regards,
**Team Horilla**

**Comment by horilla-opensource** [comment]
Hi @borishinzer ,
Please use the below commands before the runserver command.
`python manage.py migrate notifications zero`
`python manage.py makemigrations notifications`
`python manage.py migrate notifications`

This should fix the issue in the database.
Let us know if you still face the issue after this.
With Regards,
**Team Horilla**

**Comment by borishinzer** [comment]
Works for us.
