### ISSUE TITLE
Assets allocation to employee not working

### ISSUE THREAD

**Issue by asis658** [horilla-opensource/horilla#261]
# Bug Report

## Description

_[I have created some assets and allocated to employees. In assets tab it shows the assets are allocated to them but in employee profile the assets section is empty.]_

## Steps to Reproduce

1. _[Go go assets section from main dashboard and create some assets, while creating also allocate them to employees.]_

## Expected Behavior

_[These should be assets showing up at employee profile]_

## Actual Behavior

_[Currently the assets section in employee profile is empty and says no asset has been allocated even though they are already allocated.]_

## Environment

- **Django Version:** _[Django version you're using, e.g., 3.2.1]_
- **Python Version:** _[Python version, e.g., 3.10]_
- **Operating System:** _[Your OS, e.g., Ubuntu 22.04]_
- **Browser:** _[Edge]_

**Comment by horilla-opensource** [comment]
Hi @asis658 ,
We have checked from our end as both admin and as a normal employee. The asset allocation is working fine and its view for employee also.
Could you please try the same in a fresh session, it might be due to some cache issue?
If it's not solved, please let us know.

With Regards,
**Team Horilla**

**Comment by asis658** [comment]
On my end if a employee creates a asset request and admin approves then it shows up on employee profile. But if admin allocates directly from assets list(during asset creation or update later) it doesn't show up. I believe it's now how it works. I'll give another try with fresh installation may be.

**Comment by horilla-opensource** [comment]
We have checked the same workflow from our end and it's also working fine.
Can you try creating a new asset  and try allocating it to an employee ?

**Comment by asis658** [comment]
I tried again with couple of fresh installations but  still assets aren't showing up( or not actually allocated) when the owner is set from the assets page.

**Comment by horilla-opensource** [comment]
Hi @asis658 ,
Were you able to confirm the workflow with the latest code base?

With Regards,
**Team Horilla**

**Comment by asis658** [comment]
I haven't tried the latest code base yet, thanks for reminding.

**Comment by horilla-opensource** [comment]
Hi @asis658 ,
Any updates?

**Comment by asis658** [comment]
Hi, after the update the feature to allocate asset by admin without receiving the request from the employee(whish is what this thread is about) is gone.
Asset request approval is working well.
