### ISSUE TITLE
How do I edit the email template? 

### ISSUE THREAD

**Issue by XConradX** [horilla-opensource/horilla#262]
May I know how to edit the email template that the approvers receiving when an employee file a leave?

**Comment by horilla-opensource** [comment]
Hi @XConradX ,
Currently the leave mail template is directly fetched from the html code. We are working on having it customisable from the user end similar to the mail automation templates.
For now you can edit the leave mail template by updating the `base/mail_templates/leave_request_template.html` 

With Regards,
**Team Horilla**

**Comment by XConradX** [comment]
thank you! I'll update the template in html format first.
