### ISSUE TITLE
Unable the fetch clock events from biometric device.

### ISSUE THREAD

**Issue by asis658** [horilla-opensource/horilla#272]
I have zkteco biometric device imported to horilla application. The communication between app and device is fine with live capture mode enabled. But the applications isn't getting any check-in /check-out logs from the device. At the event of punch-in on device, the horilla server throws following error:

`local variable 'attendance_activity' referenced before assignment
Got an error in clock_out local variable 'attendance_activity' referenced before assignment
[30/Jul/2024 13:34:16] "GET /inbox/notifications/api/unread_list/?max=5 HTTP/1.1" 200 38`

**Comment by asis658** [comment]
I fixed it to avoid error but still can't get the punch log from biometric device.

**Comment by horilla-opensource** [comment]
Hi @asis658 ,
Can you make sure that the employee listed in the biometric is available in the Horilla database ?
You need to add users to the biometric from the Horilla app and also make sure that the badge id in the Horilla database matches with the employee id in the biometric.

With Regards,
**Team Horilla**

**Comment by asis658** [comment]
Yes employee listed on both device and horilla. Not employee_id, but, user_id in device match the user_id in horilla. when I add employee to device inside horilla app it automatically adds that user to the device so I didn't change anything on device. When I add thumb it shows the green indicator as in your images so I believe the fields are correct. Just to make sure, I changed emp_id in device to badge_id  but no luck. I still can't get the attendance log in horilla app.

**Comment by horilla-opensource** [comment]
Hi @asis658 ,
Can you please connect with teamhorilla@gmail.com on skype to discuss further on this issue as we are not able to reproduce the issue from our end. Our support team will help you solve this issue.

With Regards,
**Team Horilla**

**Comment by asis658** [comment]
Hi, I wanted to try with another fresh installation, and I still can not get attendance log from device but the error message changed  to the following 
` cannot access local variable 'attendance_activity' where it is not associated with a value
Got an error : cannot access local variable 'attendance_activity' where it is not associated with a valuc`

**Comment by asis658** [comment]
Resolved the issue contacting Teamhorilla via skype. Great support!
