### ISSUE TITLE
Bug - Leave applied,  but did a checkin/checkout | work record shows present

### ISSUE THREAD

**Issue by BhuviTheDataGuy** [horilla-opensource/horilla#275]
An employee applied for leave and it is in the requested state, after that, he did check-in and check-out. 

In work records, it shows present, We approved the leave, but again the work hours show present only. 

If the leave is approved, the work hours should show leave.

**Comment by horilla-opensource** [comment]
Hi @BhuviTheDataGuy ,
We have added a separate color code for people who are on leave, but have their attendance marked in the work record view.

![image (1)](https://github.com/user-attachments/assets/95f21abf-16ee-4e9d-97e7-3ddafad16d1b)
