### ISSUE TITLE
Not install numpy

### ISSUE THREAD

**Issue by RajapandiR** [horilla-opensource/horilla#277]
<img width="1440" alt="Screenshot 2024-08-07 at 4 54 58 PM" src="https://github.com/user-attachments/assets/a5eed7c2-2f7e-4112-a986-7126c6667d7d">

**Comment by horilla-opensource** [comment]
Hi @RajapandiR ,
Is this issue happening while running the `pip3 install -r requirements.txt` ?
Can you first explicitly install the numpy package and run the requirements installation command next ?

With Regards,
**Team Horilla**

**Comment by RajapandiR** [comment]
Hi, @horilla-opensource . 
I already tried, but same issue

**Comment by horilla-opensource** [comment]
Hi @RajapandiR ,
Which is your python version ?

With Regards,
**Team Horilla**

**Comment by RajapandiR** [comment]
Python 3.13.0.
pip 24.2

**Comment by horilla-opensource** [comment]
Can you please downgrade the python version to a stable version and try again ?
Python 3.13 is in prerelease stage and is bound to errors.
Please try it out with python 3.11 or 3.12 .

With Regards,
**Team Horilla**

**Comment by horilla-opensource** [comment]
Hi @RajapandiR ,
Were you able to work around with it?

With Regards,
**Team Horilla**

**Comment by RajapandiR** [comment]
Hi @horilla-opensource .
numpy installed.
Now new error coming 

Preparing metadata (pyproject.toml) did not run successfully.

<img width="1440" alt="Screenshot 2024-08-27 at 3 17 16 PM" src="https://github.com/user-attachments/assets/50a42c51-b5f8-418c-b1ba-f319df654585">

**Comment by RajapandiR** [comment]
I think error PyMuPDF== 1.24.5 not supported
