### ISSUE TITLE
Dashboard widgets cannot be arranged

### ISSUE THREAD

**Issue by borishinzer** [horilla-opensource/horilla#28]
**Describe the bug**
Tried to move dashboard widgets, but "On leave" seems to be stuck on top-right corner.

**Screenshots**
<img width="1464" alt="Bildschirmfoto 2023-08-10 um 21 06 48" src="https://github.com/horilla-opensource/horilla/assets/10340538/90ebe49c-b96d-4ca2-a601-12b0b3a4ba1a">

**Comment by horilla-opensource** [comment]
Hi @borishinzer ,
The "On Leave" tile is a fixed tile that we have added and cannot be moved.
We are currently working on refactoring the main dashboard and also include dashboards for other modules too, which will be published soon in the coming updates.
With Regards,
**Team Horilla**

**Comment by borishinzer** [comment]
Wow, nice. Will test later. Thank you very much for your efforts and the immediate responses. Really awesome.

**Comment by horilla-opensource** [comment]
Thank you @borishinzer . 
Your feedback also means a lot to us.
We'll keep you posted on the updates.
**Team Horilla**

**Comment by horilla-opensource** [comment]
@borishinzer Is the updates working fine?

**Comment by borishinzer** [comment]
I think the updated dashboard was not released yet, right?

**Comment by horilla-opensource** [comment]
Hi @borishinzer ,
The dashboards are already updated.
