### ISSUE TITLE
Visible [ ] Characters in Production Environment on Ubuntu 24.04 VPS

### ISSUE THREAD

**Issue by Vinoth1711** [horilla-opensource/horilla#286]
# Bug Report

### Issue Summary

The issue— [ ] characters are visible—only occurs in the production environment while  running Horilla 1.2.0 on Ubuntu 24.04 in a VPS. The issue does not occur on localhost or when deployed on IIS with Horilla 1.2.0

### Steps to Reproduce

1. Deploy the application on the production server (Ubuntu 24.04 VPS).
2. Compare the output with the localhost or IIS deployment.
3. Notice the presence of [ ] characters only in the production environment.

### Expected Behavior
The characters [ ] should not be visible in the production environment, similar to how it functions on the localhost.

### Actual Behavior
[ ] characters are visible in the production environment.

### Additional Information

1. Attached snaps on that [ ]
![image (2)](https://github.com/user-attachments/assets/fc5cfdd9-30f9-469c-a0bc-369732989813)
![image (3)](https://github.com/user-attachments/assets/218e94ae-620f-4200-be2a-66cf1d0ba497)
![image (4)](https://github.com/user-attachments/assets/93115efe-6cbe-4cbc-b920-813bbf1792f9)

**Comment by horilla-opensource** [comment]
Hi @Vinoth1711 ,
We have tried to reproduce the issue on our end with the same specifications you have mentioned as yours, but its coming out fine for us. 
Please refer to the below screenshot, also you can test it out from your end. Just visit the url mentioned in this comment to test out the instance we have hosted for testing on an AWS cloud running on Ubuntu 24.04 and python3.12.
We have tested it with both DEBUG set as True as well as False.

<img width="1470" alt="Screenshot 2024-08-20 at 12 47 03 PM" src="https://github.com/user-attachments/assets/8b900563-5789-4af7-951e-548dabecd3b9">


**Test Server Link: http://43.204.218.26/**
User credentials are admin and admin for username and password respectively.

**Comment by horilla-opensource** [comment]
Can we connect on skype at teamhorilla@gmail.com to discuss more on this issue?
