### ISSUE TITLE
Error when logging in to the application

### ISSUE THREAD

**Issue by sergej-wv** [horilla-opensource/horilla#294]
# Bug Report

## Description

Hello,

when attempting to log into the application an error is being displayed.

## Steps to Reproduce

Install application.

## Expected Behavior

User is logged into the application.

## Actual Behavior

Error displayed.

## Screenshots

```
<h1>DatabaseError
       at /login/</h1>
  <pre class="exception_value">database disk image is malformed</pre>
  
Request Method: | POST
-- | --
https://<example.com>/login/
4.2.7
DatabaseError
database disk image is malformed
/opt/horilla/horillaenv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py, line 328, in execute
base.views.login_user
/opt/horilla/horillaenv/bin/python
3.10.12
['/opt/horilla/horilla',  '/usr/lib/python310.zip',  '/usr/lib/python3.10',  '/usr/lib/python3.10/lib-dynload',  '/opt/horilla/horillaenv/lib/python3.10/site-packages']
Fri, 23 Aug 2024 13:42:21 +0200
```

## Environment

- **Django Version:** 4.2.7
- **Python Version:** 3.10
- **Operating System:** Ubuntu 22.04
- **Browser:** Firefox 129

## Additional Information

![Screenshot](https://github.com/user-attachments/assets/1505ad3e-d58a-4483-b67c-af119d9b866d)

This issue only appears when a user logs out. Logged in users have no errors.

## Priority

medium

**Comment by mahesh-makwana-web-vision** [comment]
![DatabaseError-at-login-](https://github.com/user-attachments/assets/ccb8bfc5-ba32-4ca9-a224-13e9bc555a08)

**Comment by horilla-opensource** [comment]
Hi @mahesh-makwana-web-vision @sergej-wv ,
The issue is not related to the code base of Horilla and is directly related to the Sqlite3 database.
Please check the answer in the below stackoverflow link
[SQLite3 database or disk is full / the database disk image is malformed](https://stackoverflow.com/questions/5274202/sqlite3-database-or-disk-is-full-the-database-disk-image-is-malformed)
