### ISSUE TITLE
SMTP Mail server having issues in sending?

### ISSUE THREAD

**Issue by XConradX** [horilla-opensource/horilla#301]
Hi Horilla team,

I've setup my smtp server and I'm getting this error? I've checked the directory and the file is there.
app password and other needed requirements are there

![Screenshot 2024-08-28 154442](https://github.com/user-attachments/assets/31a60152-803f-4663-a7bd-c86e1bc14f25)

**Comment by akravits** [comment]
Same in Ubuntu, is this resolved somehow?

<img width="391" alt="Image" src="https://github.com/user-attachments/assets/55748cfb-3b05-4698-956b-db618a7e5ed3" />
