### ISSUE TITLE
Settings.py Mail Server

### ISSUE THREAD

**Issue by fixDiss** [horilla-opensource/horilla#316]
we are trying to manually configure the email setting in setting.py. Eventually we cant find this code in file.
![email](https://github.com/user-attachments/assets/2c1b2614-0136-4cc9-b742-1ff772fc6c07)

**Comment by horilla-opensource** [comment]
Hi @fixDiss ,
Apologize for the confusion. We have made the mail configuration settings through the frontend itself.
Users can now setup the mail configuration from the UI itself. For that go to the _Settings_ . In the _Settings_ page, under the _General_ tab, you'll find option for _Mail Server_. Click on _Add_ and provide the necessary details.

Please refer the below blog also: 
[How to Set Up Mail Server in Horilla HRMS [2024]](https://www.horilla.com/blogs/how-to-set-up-mail-server-in-horilla-hrms/)

With Regards,
**Team Horilla**

**Comment by fixDiss** [comment]
Actually we tried this  but it seems not working. please see configuration below.

![image](https://github.com/user-attachments/assets/02980b2e-6953-4072-8879-08bacbe7d154)
