### ISSUE TITLE
Issues encountered when you turn off limit leave days in creation of leaves. 

### ISSUE THREAD

**Issue by XConradX** [horilla-opensource/horilla#318]
I tried turning off limit leaves 
<img width="608" alt="image" src="https://github.com/user-attachments/assets/91411016-99ec-41bf-a128-206a176f14d8">
My database is mariadb. see attached txt for error report.
[bug.txt](https://github.com/user-attachments/files/16883085/bug.txt)

**Comment by horilla-opensource** [comment]
Hi @XConradX ,
The fix is updated in the latest commit.
The issue was with an `inf` attribute which is not present in MySQL based databases. So we have added a large value to deal with the issue.

Please check and let us know if you have any questions or concerns.

With Regards,
**Team Horilla**

**Comment by XConradX** [comment]
thank you!
