### ISSUE TITLE
Cannot Check & Uncheck Employees Properly Under Biometric Devices -> Employees

### ISSUE THREAD

**Issue by centaurusgod** [horilla-opensource/horilla#319]
All the employees aren't selected when selecting the Employee checkbox udner Biometric device -> Attendance.
![image](https://github.com/user-attachments/assets/0062cc82-45e0-43ff-bba9-07ade8ea35fa)

**Error causing code:**
horilla/biometric/static/actions.js
Line Number: 33
Improper & double closing brackets
![image](https://github.com/user-attachments/assets/5a0e2b3d-f107-420e-be22-dbc4d04dc403)
`$(".all-bio-employee").change(function (e) {
  var is_checked = $(this).is(":checked");
  if (is_checked) {
    $(".all-bio-employee-row").prop("checked", true);
  } else {
    $(".all-bio-employee-row".prop("checked", false));
  }
});`

**Fix**
Adding a closing bracket & removing unnecessary one.
`$(".all-bio-employee").change(function (e) {
var is_checked = $(this).is(":checked");
if (is_checked) {
$(".all-bio-employee-row").prop("checked", true);
} else {
$(".all-bio-employee-row").prop("checked", false);
}
});`

@horilla-opensource

**Comment by horilla-opensource** [comment]
Hi @centaurusgod ,
Thanks for notifying us with the issue in the code.
We have updated that in the latest commit.

With Regards,
**Team Horilla**
