### ISSUE TITLE
Error with the database

### ISSUE THREAD

**Issue by Tarzan22** [horilla-opensource/horilla#32]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Tarzan22** [comment]
Sorry wo default wala chala gaya.


The Issues is when we  run the server after following the complete steps we receive a error while we are trying to login 

OperationalError at /
no such column: attendance_attendance.is_validate_request

**Comment by Tarzan22** [comment]
Sorry the issue was with the index.html file with the check in and check out option. It is requested to kindly resolve this

**Comment by Tarzan22** [comment]
There is an issue with the attendance part please look into it.

**Comment by horilla-opensource** [comment]
Hi @Tarzan22 ,
Thanks for the feedback.
We'll look into the issues.
The issues mentioned above are mainly due to the demo database inconsistency, we think.
We'll fix it soon and update the demo database.
Or else you can also check with a new database.
With Regards,
**Team Horilla**

**Comment by Tarzan22** [comment]
Not working with the new database as well 
It was working fine earlier.. And I am interested in using the earlier copy of horilla which was working... Can you help me out with it

**Comment by horilla-opensource** [comment]
@Tarzan22,
If you are willing to test the software, please try to use the dev branch code currently as we are testing the latest commits and the new database will be pushed by today night only after testing.
You can make use of the dev branch([https://github.com/horilla-opensource/horilla/tree/dev] ) to test out the latest beta version.

**Comment by horilla-opensource** [comment]
Hi @Tarzan22 ,
Please try out the latest commit code in the master branch.
We have fixed the issues and updated the database.
Let us know if you face any issues with the latest code.
With Regards,
**Team Horilla**

**Comment by Tarzan22** [comment]
![image](https://github.com/horilla-opensource/horilla/assets/63293612/863af309-7a77-4500-bf06-0cc3ec8f0bed)
![image](https://github.com/horilla-opensource/horilla/assets/63293612/67fadd84-df28-4d24-8b82-1a9f2d83d831)
 Please look at these images for better understanding this happens the moment we log in.

**Comment by horilla-opensource** [comment]
Hi @Tarzan22 ,
If you are using Django 4.0 or above, please add the below code in your settings.py.
`CSRF_TRUSTED_ORIGINS = ['https://example.com']
`
Let us know if you still face any issues.
With Regards,
**Team Horilla**

**Comment by Tarzan22** [comment]
Thank You it is working fine now...

**Comment by horilla-opensource** [comment]
Happy to hear.
We are closing this issue as its fixed now.
With Regards,
**Team Horilla**
