### ISSUE TITLE
Customise branding, colors and font family.

### ISSUE THREAD

**Issue by amanattrish** [horilla-opensource/horilla#328]
# Feature Request

## Description

Options to customise branding for companies. Like changing primary and secondary colors, font family, logo, etc.

## Use Case

It will blend perfectly with company branding who would be using it.

## Proposed Solution

There should be a config file where we can put those values to customise the branding.

## Benefits

For small companies, it will be a great opportunity to create sense of building the branding who would be using it.

## Additional Information

_[Any other relevant information, details, or examples related to the feature request.]_

## Labels

feature-request

## Priority

medium

**Comment by horilla-opensource** [comment]
Hi @amanattrish ,
We do have a white labelling feature already in Horilla, where the Horilla logo's will be replaced by the HQ company's logo.
For enabling the white labelling feature, in the file `horilla/horilla_apps.py`, you'll find a variable named _WHITE_LABELLING_ set to _False_ , change its value to _True_ [(WHITE_LABELLING)](https://github.com/horilla-opensource/horilla/blob/4a464728f30fd58ebfc308eef318068a32b9535e/horilla/horilla_apps.py#L56)

Please let us know if you have any questions or concerns.

With Regards,
**Team Horilla**

**Comment by amanattrish** [comment]
Once we make it to True, where do we make changes to add our logos, and change other things?

**Comment by horilla-opensource** [comment]
The details are taken from the HQ company.

**Comment by horilla-opensource** [comment]
You can find it in the company form.
<img width="755" alt="Screenshot 2024-09-19 at 2 49 43 PM" src="https://github.com/user-attachments/assets/613a8161-f6eb-4db6-8683-3a78092dd791">

**Comment by amanattrish** [comment]
I guess it is only possible from CSS as of 22 Sep 2024
