### ISSUE TITLE
AttributeError 

### ISSUE THREAD

**Issue by TSmiley12** [horilla-opensource/horilla#33]
AttributeError at /employee/employee-view-update/1/
'NoneType' object has no attribute 'reporting_manager'
Request Method:	GET
Request URL:	http://127.0.0.1:8000/employee/employee-view-update/1/
Django Version:	4.2.4
Exception Type:	AttributeError
Exception Value:	
'NoneType' object has no attribute 'reporting_manager'
Exception Location:	C:\Users\smile\OneDrive\Desktop\Django-Projects\horilla-master\employee\views.py, line 233, in employee_view_update
Raised during:	horilla.decorators.wrapped_view
Python Executable:	C:\Users\smile\OneDrive\Desktop\Django-Projects\horilla-master\env\scripts\python.exe
Python Version:	3.10.11

I believe the problem is coming from the below code.

@login_required
@manager_can_enter("employee.view_employee")
def employee_view_individual(request, obj_id):
    """
    This method is used to view profile of an employee.
    """
    employee = Employee.objects.get(id=obj_id)
    user = Employee.objects.filter(employee_user_id=request.user).first()
    if user.reporting_manager.filter(
        employee_id=employee
    ).exists() or request.user.has_perm("employee.change_employee"):
        return render(request, "employee/view/individual.html", {"employee": employee})
    return HttpResponseRedirect(
        request.META.get("HTTP_REFERER", "/employee/employee-view")
    )

**Comment by horilla-opensource** [comment]
Hi @TSmiley12,
We think the issue is coming because you have created the admin user using the Django's default createsuperuser command.
In Horilla, to create an admin employee, please use the createhorillauser command which automatically assigns all the admin user permissions to the particular user.
`sudo python3 manage.py createhorillauser`

Let us know if you still face the issue after this.
With Regards,
**Team Horilla**

**Comment by nikhilcybro** [comment]
Hi @TSmiley12 ,
Were you able to confirm with the solution mentioned above?
With Regards,
**Team Horilla**

**Comment by horilla-opensource** [comment]
Hi @TSmiley12 ,
Were you able to confirm with the solution mentioned above?
With Regards,
**Team Horilla**

**Comment by horilla-opensource** [comment]
@TSmiley12 Could you elaborate the issue you are facing?
With Regards,
**Team Horilla**

**Comment by TSmiley12** [comment]
Thank you for your response. I have created a staff of about 30 on an excel
spreadsheet and wanted to try and upload all the data on the spreadsheet on
to the system. Is there a way to to upload the data from the spreadsheet
into the system?
Thanks regards.

**Comment by horilla-opensource** [comment]
Hi @TSmiley12 ,
Please refer the below blog for the detailed steps for importing employees into the system.
[How to Create Employee Data Setup in Horilla HR Software](https://www.horilla.com/blogs/how-to-create-employee-data-setup-in-horilla-hr-software/#gsc.tab=0)
With Regards,
**Team Horilla**

**Comment by horilla-opensource** [comment]
Hi @TSmiley12 ,
Were you able to check with the blog for the solution?

**Comment by TSmiley12** [comment]
Yes, I did. But it didn't work out.

**Comment by horilla-opensource** [comment]
What is the issue that you are facing?

**Comment by horilla-opensource** [comment]
@TSmiley12 Any updates?

**Comment by TSmiley12** [comment]
Yes, it's working now.
