### ISSUE TITLE
Employee Permission

### ISSUE THREAD

**Issue by loanduong02** [horilla-opensource/horilla#342]
I want to grant permission to an employee who only has approval rights but is not allowed to edit. Does the current version allow this?

**Comment by horilla-opensource** [comment]
Hi @loanduong02 ,
No the current Horilla version does not have a similar feature.

**Comment by loanduong02** [comment]
> Hi @loanduong02 , No the current Horilla version does not have a similar feature.

I want to add a data field to the table because in the current version there are some missing fields for my company's needs. Does the current version allow it, or is there a way to customize it?

**Comment by horilla-opensource** [comment]
> > Hi @loanduong02 , No the current Horilla version does not have a similar feature.
> 
> I want to add a data field to the table because in the current version there are some missing fields for my company's needs. Does the current version allow it, or is there a way to customize it?

Hi @loanduong02 ,
In the current version, the only way to add custom fields into the company is from the backend models code. You'll have to make customisation in the code to achieve the same.

But we do have a feature planned in our next version, where people can have custom fields directly from the frontend.

**Comment by loanduong02** [comment]
> > > Hi @loanduong02 , No the current Horilla version does not have a similar feature.
> > 
> > 
> > I want to add a data field to the table because in the current version there are some missing fields for my company's needs. Does the current version allow it, or is there a way to customize it?
> 
> Hi @loanduong02 , In the current version, the only way to add custom fields into the company is from the backend models code. You'll have to make customisation in the code to achieve the same.
> 
> But we do have a feature planned in our next version, where people can have custom fields directly from the frontend.

I couldn't find any documentation for these 2 items. Can you provide it to me?
![image](https://github.com/user-attachments/assets/5ba1b230-b4e6-448f-b7da-1775d4dab4d0)

**Comment by horilla-opensource** [comment]
Hi @loanduong02 ,
Please find the documentation of Payroll module in the below link. (PS: This is a draft of the documentation, we'll be updating it on our website soon)

[PAYROLL DOC](https://drive.google.com/file/d/1HnEGHwCDr8-TtyZZlfK2q3Q4K7Y0Hh38/view?usp=sharing)
