### ISSUE TITLE
Porgramming error; column employee_employee.is_from_onboarding does not exist

### ISSUE THREAD

**Issue by vanyell** [horilla-opensource/horilla#361]
# Bug Report

ProgrammingError at /attendance/dashboard

## Description

After pulling latest version to upgrade existing installation, immediately got the error upon accessing the site

## Steps to Reproduce

Pulled latest from github
ran python manage.py makemigrations and python manage.py migrate
Returned no changes and no migrations to apply respectively

## Expected Behavior

should be able to access Horilla UI

## Actual Behavior

Error page appeared

## Screenshots

![image](https://github.com/user-attachments/assets/77be0fbd-d11d-4225-b7ca-de383ec2d61a)

## Environment

- **Django Version:** 4.11
- **Python Version:** 3.11.2 
- **Operating System:** Ubuntu 22.04
- **Browser:** firefox

## Additional Information

columns from Postgres table employee_employee
 id | badge_id | employee_first_name | employee_last_name | employee_profile | email | phone | address | country | state | city | zip | dob | gender | qualification | experience | marital_status | children | emergency_contact | emergency_contact_name | emergency_contact_relation | is_active | additional_info | employee_user_id_id 

## Possible Solution

_[If you have any ideas or suggestions on how to fix the issue, feel free to provide them here. This is optional.]_

## Labels

_[If your project uses labels, suggest any labels that might apply to this issue, such as 'bug', 'needs investigation', etc.]_

## Priority

_[Specify the priority level for this issue, such as 'high', 'medium', 'low', etc.]_

## Assignees

_[If you want to suggest an assignee or tag a specific person to look into this issue, mention their GitHub username here.]_

## Related Issues

_[If there are any related issues or pull requests, mention them here. This is optional.]_

**Note:** _Remember to search through existing issues before submitting a new one to ensure that the issue hasn't been reported already. Provide as much information as possible to help the maintainers understand and address the problem effectively._

**Comment by horilla-opensource** [comment]
Hi @vanyell ,
Can I confirm whether you are using the test database or your database?

With Regards,
**Team Horilla**

**Comment by vanyell** [comment]
Own database using postgresql

**Comment by horilla-opensource** [comment]
> Own database using postgresql

Please run the commands and try again.
```
python3 manage.py makemigrations employee
python3 manage.py migrate employee
```

**Comment by vanyell** [comment]
Didn't work.

![image](https://github.com/user-attachments/assets/a49bc3ba-9c62-4489-b601-02d940dba828)

**Comment by horilla-opensource** [comment]
In that case, can you please share the contents of the last migration file in the employee app?

**Comment by vanyell** [comment]
> In that case, can you please share the contents of the last migration file in the employee app?

Where should I get that?

**Comment by horilla-opensource** [comment]
You can find the file inside the _employee/migrations_ folder.
Please share the contents of the last written file inside that folder.

**Comment by vanyell** [comment]
> You can find the file inside the _employee/migrations_ folder. Please share the contents of the last written file inside that folder.

wait... I think I got what you want to see...  let me try once more

**Comment by horilla-opensource** [comment]
Okay

**Comment by vanyell** [comment]
[migrations.tar.gz](https://github.com/user-attachments/files/17239969/migrations.tar.gz)


Please see attached

**Comment by horilla-opensource** [comment]
Hi @vanyell ,
Please comment out or remove the line 79  [`('is_from_onboarding', models.BooleanField(blank=True, default=False, editable=False, null=True)),`]
 from the _0001_initial.py_ and run the migrate command .

`python manage.py migrate`

After that run the makemigrations and migrate command again. This should fix the issues.
```
python manage.py makemigrations
python manage.py migrate
```

**Comment by vanyell** [comment]
Following columns are triggering erros

- Add field is_directly_converted to employee ... changed this like suggested.. Error gone.

- Add field currency_symbol to payrollsettings -> this one generated a treceback after following the previous steps 
(venv) root@rubaiyat:/var/www/html/horilla# python manage.py migrate
Operations to perform:
  Apply all migrations: accessibility, admin, asset, attendance, auditlog, auth, base, biometric, contenttypes, django_apscheduler, employee, helpdesk, horilla_audit, horilla_automations, horilla_documents, horilla_views, leave, notifications, offboarding, onboarding, payroll, pms, recruitment, sessions
Running migrations:
  Applying payroll.0002_payrollsettings_currency_symbol...Traceback (most recent call last):
  File "/var/www/html/horilla/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 87, in _execute
    return self.cursor.execute(sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.DuplicateColumn: column "currency_symbol" of relation "payroll_payrollsettings" already exists

-

**Comment by horilla-opensource** [comment]
Did you clear out the existing files from the migrations folder of each apps after pulling latest code ?

**Comment by vanyell** [comment]
I'll do those again... will update afterwards.
Yahoo Mail: Search, Organize, Conquer 
 
  On Thu, Oct 3, 2024 at 2:50 PM, ***@***.***> wrote:   


Did you clear out the existing files from the migrations folder of each apps after pulling latest code ?

**Comment by horilla-opensource** [comment]
Hi @vanyell ,
Please don't do that. I meant to ask that because by looking at the employee migrations file, there was only a single migrations file which signified you have ran the makemigrations command only once in the database.

The files inside the migrations folder should not be removed.

**Comment by vanyell** [comment]
Oh.. then I didn't remove anything. Just did a clone to a new directory and reused  existing psql db previously  populated 
Yahoo Mail: Search, Organize, Conquer 
 
  On Thu, Oct 3, 2024 at 3:02 PM, ***@***.***> wrote:   


Hi @vanyell ,
Please don't do that. I meant to ask that because by looking at the employee migrations file, there was only a single migrations file which signified you have ran the makemigrations command only once in the database.

The files inside the migrations folder should not be removed.

**Comment by horilla-opensource** [comment]
Yes, that's the issue.
Because each time when you clone to a new directory it doesn't have the migrations file inside it. 
What makemigrations does is actually create the sql schema for populating the database. But since there is no migrations file when you clone the repository, it generates the schema for all the models and fields.
Since you are using the database which already has the models and fields from the previous migrations, this gets in conflict with the new schema and that's the reason you are facing the issue.

The thing you can do is rather the cloning the repo each time to a new directory you can make use of the git's `pull `
 command.

Please let us know if you need assistance in that. We can provide an online meeting to fix the issue that you are facing right now and also explain to you how to manage the code workflow more efficiently next time.

With Regards,
**Team Horilla**

**Comment by vanyell** [comment]
Thanks. Sorry for the bother....

Yahoo Mail: Search, Organize, Conquer 
 
  On Thu, Oct 3, 2024 at 3:13 PM, ***@***.***> wrote:   


Yes, that's the issue.
Because each time when you clone to a new directory it doesn't have the migrations file inside it.
What makemigrations does is actually create the sql schema for populating the database. But since there is no migrations file when you clone the repository, it generates the schema for all the models and fields.
Since you are using the database which already has the models and fields from the previous migrations, this gets in conflict with the new schema and that's the reason you are facing the issue.

The thing you can do is rather the cloning the repo each time to a new directory you can make use of the git's pull 
command.

Please let us know if you need assistance in that. We can provide an online meeting to fix the issue that you are facing right now and also explain to you how to manage the code workflow more efficiently next time.

With Regards,
Team Horilla

**Comment by horilla-opensource** [comment]
Please let us know if you need the assistance in fixing your current database.

**Comment by vanyell** [comment]
I'll try to sort it on my end first....

Yahoo Mail: Search, Organize, Conquer 
 
  On Thu, Oct 3, 2024 at 3:17 PM, Peter ***@***.***> wrote:   Thanks. Sorry for the bother....

Yahoo Mail: Search, Organize, Conquer 
 
  On Thu, Oct 3, 2024 at 3:13 PM, ***@***.***> wrote:   


Yes, that's the issue.
Because each time when you clone to a new directory it doesn't have the migrations file inside it.
What makemigrations does is actually create the sql schema for populating the database. But since there is no migrations file when you clone the repository, it generates the schema for all the models and fields.
Since you are using the database which already has the models and fields from the previous migrations, this gets in conflict with the new schema and that's the reason you are facing the issue.

The thing you can do is rather the cloning the repo each time to a new directory you can make use of the git's pull 
command.

Please let us know if you need assistance in that. We can provide an online meeting to fix the issue that you are facing right now and also explain to you how to manage the code workflow more efficiently next time.

With Regards,
Team Horilla

**Comment by vanyell** [comment]
I was able to fix things from my end.

Question about the git workflow though... It would be better to open that one topic under the discussions section.
