### ISSUE TITLE
Leaves are not showing on dashboard

### ISSUE THREAD

**Issue by borishinzer** [horilla-opensource/horilla#37]
**Describe the bug**
Although sick leaves are approved, they are not showing on the dashboard

**Expected behavior**
Actual leaves are showing on dashboard

**Screenshots**
![Bildschirmfoto 2023-08-16 um 09 22 18](https://github.com/horilla-opensource/horilla/assets/10340538/009b5792-e30f-46a3-a0e6-14eac9f96b5e)
![Bildschirmfoto 2023-08-16 um 09 21 25](https://github.com/horilla-opensource/horilla/assets/10340538/3e6c8b1a-93a8-4215-b306-1adbf8514124)

**Comment by horilla-opensource** [comment]
Hi @borishinzer ,
We have fixed the issue and updated the code.
Please check [commit](https://github.com/horilla-opensource/horilla/commit/d89fd76aa4e9cbda346f7621fb3d79fb168df4e4)
With Regards,
**Team Horilla**

**Comment by horilla-opensource** [comment]
Hi @borishinzer ,
We've addressed the reported issue and believe it's now resolved. Could you kindly confirm if you're still facing any problems?
With Regards,
**Team Horilla**

**Comment by borishinzer** [comment]
Still not working for us.

**Comment by horilla-opensource** [comment]
@borishinzer 
We have tested this case, and its working fine.
Could you check by deleting the existing leave data's and creating a new request again with the latest commit?
If the issue still persists, could you provide us with a screen recording of your instance and email it to us at info@horilla.com ?
With Regards,
**Team Horilla**

**Comment by borishinzer** [comment]
Works now.
