### ISSUE TITLE
Getting issue while loading candidates in recruitment pipeline 

### ISSUE THREAD

**Issue by aliraza923** [horilla-opensource/horilla#371]
I'm encountering an issue in the recruitment pipeline section. The stage data inconsistently loads sometimes one stage loads successfully, while other times it keeps searching indefinitely without retrieving the data.

![Screenshot 2024-10-16 at 1 49 12 AM](https://github.com/user-attachments/assets/836c097a-a3e0-47d2-9ffa-924b8e6ace7a)

I investigated the problem and found that it stems from the **/recruitment/candidate-stage-component?stage_id=9** API call. The strange part is that each time, one of the calls successfully retrieves data, but others are failing with the following error:

![Screenshot 2024-10-16 at 1 49 51 AM](https://github.com/user-attachments/assets/e6c242cf-90a7-4b73-b748-56f3b79f1c05)

**Comment by horilla-opensource** [comment]
Hi @aliraza923 ,

Can we know the hosting method that you have used for hosting Horilla?

With Regards,
**Team Horilla**

**Comment by aliraza923** [comment]
I hosted it on the Digital Ocean Ubuntu server, where Gunicorn & nginx are used to serve the application, Overall, the application is working fine only getting the issue in the recruitment pipeline section.

**Comment by horilla-opensource** [comment]
Hi @aliraza923 ,

Can you try clearing out the cache and trying again?

With Regards,
**Team Horilla**

**Comment by aliraza923** [comment]
Still no luck :(

**Comment by horilla-opensource** [comment]
Do you have experience with redis cache ?

**Comment by aliraza923** [comment]
Yes!

**Comment by horilla-opensource** [comment]
Great! 
Please let us know if you face any other issues or if you have any queries.
