### ISSUE TITLE
Shift issues

### ISSUE THREAD

**Issue by Kuttypillai** [horilla-opensource/horilla#378]
# Bug Report

While changing shift in attendance request form, the minimum hour is not working properly it disappears when we change the date.

**Comment by horilla-opensource** [comment]
Hi @Kuttypillai ,
Can you provide the screenshot of the same?

**Comment by RaagulElangovan** [comment]
> Hi @Kuttypillai , Can you provide the screenshot of the same?

Thank you for your assistance; the issue has been resolved. I have reviewed the latest release of the horilla-main code, and everything is now functioning as expected.
