### ISSUE TITLE
There Seems to be an issue with the new commit 

### ISSUE THREAD

**Issue by Tarzan22** [horilla-opensource/horilla#38]
![image](https://github.com/horilla-opensource/horilla/assets/63293612/401383d4-19b6-446d-bbf1-e71933654604)
This is the error message being displayed while I try to log in

**Comment by Tarzan22** [comment]
It is requested to please fix this

**Comment by horilla-opensource** [comment]
@Tarzan22 ,
Please do the migration commands as we have made changes in the employee model.
`python3 manage.py makemigrations`
`python3 manage.py migrate`
With Regards,
**Team Horilla**

**Comment by Tarzan22** [comment]
![image](https://github.com/horilla-opensource/horilla/assets/63293612/87ac0ad0-e67e-4bed-8b11-3855cf3c194a)
No migrations to apply is what I get when I try to run the migrations

**Comment by Tarzan22** [comment]
@horilla-opensource Please suggest what can be done

**Comment by horilla-opensource** [comment]
@Tarzan22 ,
Please try the below commands to try if you are trying out with the dummy data's.
 `
   python3 manage.py migrate employee zero

   python3 manage.py makemigrations employee

   python3 manage.py migrate employee zero

   `

**Comment by Tarzan22** [comment]
THANK YOU TEAM

The issue was resolved when i just deleted the database and ran the migrations again

**Comment by Tarzan22** [comment]
it is working fine now
