### ISSUE TITLE
[SECURITY] Multiple security issues with horilla

### ISSUE THREAD

**Issue by Sp1d3rL1** [horilla-opensource/horilla#397]
Hello, I have identified multiple serious security vulnerabilities in the latest version v1.2.1 of horilla, the details of the issue are not easy to disclose here, and have sent you the details of the vulnerability via email [mnss2021@163.com](url).
I hope to work with you soon to fix the problem!

**Comment by horilla-opensource** [comment]
Hi @Sp1d3rL1 ,

Thank you for pointing that out, and we truly appreciate the time and effort you’ve taken to help make Horilla a better product.

The team is reviewing the same and will get back to you once it's done.

With Regards,
**Team Horilla**

**Comment by horilla-opensource** [comment]
Hi @Sp1d3rL1 ,

The mentioned issues have been successfully fixed and updated to the master.

Thank you for the suggestions and feedback. 

With Regards,
**Team Horilla**
