### ISSUE TITLE
Missing View for Inactive Employees???

### ISSUE THREAD

**Issue by vanyell** [horilla-opensource/horilla#398]
### Discussed in https://github.com/horilla-opensource/horilla/discussions/393

<div type='discussions-op-text'>

<sup>Originally posted by **vanyell** November 19, 2024</sup>
While editing an employee profile, there is a toggle for "Is active" status. What is the exact use of this? When toggled to turn off, that particular employee cannot been seen in the Employee View even by the superadmin. Can someone clarify the use of this toggle button? Also, how to change it back.

![image](https://github.com/user-attachments/assets/4ff1785e-fdd1-4284-a00f-0ce279ae9cd7)
</div>

**Comment by horilla-opensource** [comment]
Hi @vanyell ,

Sorry we have missed your message in discussions.

The Is active button in the employee view is for archiving the employees record.

Let's say the employee has resigned and he is no longer working in the firm, so his data need not be visible in the system by default. For that you can toggle the value of this field to false.

In case if you wish to see that employees record or want to make it active, you can make use of the filter option in employee view.

Click _Filter_ > _Advanced_ >_Is Active_ and change it's value to _No_
<img width="1433" alt="Screenshot 2024-11-25 at 2 44 36 PM" src="https://github.com/user-attachments/assets/cad298a1-492b-4dc7-be68-a0a243055af4">

This is should show you all the employees who are not active.

**Comment by bokanoo** [comment]
I can't find this feature in the current version of Horilla. Where can I locate the button to set an employee as active or inactive?

**Comment by horilla-opensource** [comment]
Hi @bokanoo ,

![Image](https://github.com/user-attachments/assets/698cc358-a154-4279-8ec1-79b4b14485e0)

You can use the Archive button to set an employee as inactive. Once an employee is archived, an Unarchive button will appear in place of the Archive button, allowing you to reactivate the employee when needed.
