### ISSUE TITLE
Cannot Login after install app

### ISSUE THREAD

**Issue by jignesh03** [horilla-opensource/horilla#402]
# Bug Report
Cannot Login after install app
## Description

using admin admin user name and password with sqllite db unable to login  giving error 

OperationalError at /
no such column: attendance_attendance.batch_attendance_id_id

## Steps to Reproduce

open browser and trying to login

## Expected Behavior

It should login and open homepage 

## Actual Behavior

Giving Erorro 

## Screenshots

Attached  Herewith 
![image](https://github.com/user-attachments/assets/0a6cdfdc-03f8-4a0d-bbbe-f29bacf80497)

**Comment by horilla-opensource** [comment]
Hi @jignesh03 ,

The issue was with the Test database and we have updated it. Please pull the latest code base and try again.

With Regards,
**Team Horilla**

**Comment by jignesh03** [comment]
THANK YOU
IT IS SOLVED
