### ISSUE TITLE
How to setup multiple approvals for one department

### ISSUE THREAD

**Issue by XConradX** [horilla-opensource/horilla#409]
I am setting up multiple approval for one of the department but I am not sure how to setup. I need to apply two approval levels for the leave request without any condition. how to setup?

![image](https://github.com/user-attachments/assets/8262b509-7129-4431-9b26-a3e6ef48bc82)

**Comment by horilla-opensource** [comment]
Hi @XConradX ,

The condition defined in the image ensures that any leave request submitted by employees from the S/W Dept with Requested Days greater than or equal to 1 day will require approval from the specified managers.

First, Alexander Smith (PEP16) needs to approve the request. After his approval, the request will move to Abigail Roberts (PEP15) on the Horilla portal. Once he approves it, the request will proceed to Adam Luis (PEP00) on the Horilla portal. After his approval, the leave request will be fully approved. If any manager rejects the request, it will be completely rejected.

In cases where a superuser approves the request, it will be considered fully approved immediately.

This setup ensures that leave requests meeting these criteria are reviewed by the designated managers, ensuring proper oversight and compliance with organizational policies.

![multiple_approve](https://github.com/user-attachments/assets/473666ab-001c-4b01-91f4-24ba016976c4)


Please let us know if you have any questions or concerns.

With Regards,
**Team Horilla**

**Comment by XConradX** [comment]
thank you so much!
