### ISSUE TITLE
ISSUE IMPORTING EMPLOYEE FROM TEMPLATE

### ISSUE THREAD

**Issue by nthakuri** [horilla-opensource/horilla#423]
Hello @horilla-opensource team,

Currently I am facing an issue, where it shows error :
**User ID Error
User with the email ID already exists** while importing the excel file

example user email : test@gmail.com

Though the employee test@gmail.com does not exist, it show the above error. But when I try to create new employee with gmail test@gmail.com  from GUI itself, it works!!
I tried accessing the database, the user is not present inside the employee_employe table, but the user exists in auth_user table. Is there any key reference which might affect the workflow? 

Also I created another test user inside auth_user to ensure if it was the cause of issue and try importing the employee again using excel under employee dashboard so make sure if duplicate error was from the auth_user table, but the user was imported successfully, but not other real users. What could be the possible solution for this?

**Comment by wwwardany** [comment]
Hello,

I am facing the same issue and I cannot seem to add all my employees. I noticed you closed the ticket, were you able to find a fix?
