### ISSUE TITLE
Filters are not permanent

### ISSUE THREAD

**Issue by borishinzer** [horilla-opensource/horilla#48]
# Bug Report
When you select a filter (eg. for leave requests), once you approve a request the filter get removed. This makes the work inefficient. It would be better to show selected filters and have them removed on demand.

**Comment by horilla-opensource** [comment]
Hi @borishinzer ,
We have added the fix for the issue.
Please check[ [ADD] GENERAL: Save filter and loading animation ](https://github.com/horilla-opensource/horilla/commit/82ec0dc862acb29c7fe47d6acc052859085092a3)

With Regards,
**Team Horilla**

**Comment by horilla-opensource** [comment]
Hi @borishinzer ,
Were you able to test this out?

With Regards,
**Team Horilla**

**Comment by borishinzer** [comment]
Not yet, sorry.

**Comment by horilla-opensource** [comment]
No issues,
Do let us know once you have been able to go through the updates.
Thanks.
With Regards,
**Team Horilla**

**Comment by borishinzer** [comment]
Resolved. Thank you very much.
