### ISSUE TITLE
No emails about leave requests or other important notications?

### ISSUE THREAD

**Issue by borishinzer** [horilla-opensource/horilla#49]
# Bug Report
When a new leave request is filed, a notification to the supervisor (best via email) should be sent. 
Also if the request was approved or denied to the user.

**Comment by horilla-opensource** [comment]
Hi @borishinzer ,
We have updated the solution for this issue in the commit: [ [UPDT] LEAVE: Sending mail to reporting managers while request creation and related activities](https://github.com/horilla-opensource/horilla/commit/e098cf03b27bfa84e3237b4ff2d840e9691e27ef)

Please check and do let us know if you face any more issues.

With Regards,
**Team Horilla**

**Comment by borishinzer** [comment]
Awesome. Thank you.
