### ISSUE TITLE
Contributing Guidelines missing

### ISSUE THREAD

**Issue by sree-hari-s** [horilla-opensource/horilla#52]

**Comment by horilla-opensource** [comment]
Hi @sree-hari-s ,
Thanks for the feedback.
The contributing guidelines/ steps are added to the repo.
[[ADD] CONTRIBUTING.md ](https://github.com/horilla-opensource/horilla/commit/f6fc85c4448430e87fdec2e79911e9d11f81af78)

With Regards,
**Team Horilla**
