### ISSUE TITLE
Local setup issue while migrating

### ISSUE THREAD

**Issue by sree-hari-s** [horilla-opensource/horilla#53]
# Bug Report

## Description

Issue encountering while trying to run

```bash
python manage.py makemigrations
```

## Steps to Reproduce

during the initial setup 
Cloned the repo
Created virtual environment
installed dependencies
tried to make migration and error occured

## Expected Behavior

successful migration of database

## Actual Behavior

from django.utils.translation import ugettext_lazy as _
ImportError: cannot import name 'ugettext_lazy' from 'django.utils.translation

## Screenshots

![image](https://github.com/horilla-opensource/horilla/assets/48482060/1ec1893b-a2e1-4942-beff-3908f05d6a21)

## Environment

- **Django Version:**  4.2.5
- **Python Version:** 3.11.3
- **Operating System:** Windows 11

## Priority

medium

**Comment by sree-hari-s** [comment]
https://forum.djangoproject.com/t/importerror-cannot-import-name-ugettext-lazy-from-django-utils-translation/10943/4

**Comment by horilla-opensource** [comment]
Hi @sree-hari-s , 
The issue is fixed.
Please check with the latest code and provide your feedback.
[[IMP] TRANSLATION: Fix migration issue on initial setup of Horilla
](https://github.com/horilla-opensource/horilla/commit/e2656f897f0644b99e745204a0ad6ff21baa11fa)

With Regards,
**Team Horilla**

**Comment by sree-hari-s** [comment]
Yes now it is working fine.

It would be nice to mention we cannot create a user with these details while executing 

```bash
python manage.py createhorillauser
```

![image](https://github.com/horilla-opensource/horilla/assets/48482060/64f70621-e94c-46ac-bc51-24cf18bfa73d)

**Comment by horilla-opensource** [comment]
Hi @sree-hari-s ,
Its only for the test database this won't work, as there is already a user with username _admin_ in the test database.
Sorry for the misconception happened there.
We'll update the details there.
For a fresh database, the username _admin_ will work.

With Regards, 
**Team Horilla**
