### ISSUE TITLE
Group rights are not applyable to employees

### ISSUE THREAD

**Issue by borishinzer** [horilla-opensource/horilla#57]
# Bug Report
The assignment of group access rights is very tedious. It is unclear how to assign a group "employee" to a certain person. Concrete: Employees need to see their hour account, their detailed time trackings (including breaks). We were not able to figure this out.

**Comment by borishinzer** [comment]
It's important to mention that employees need  to *their own* detail time trackings and over/under times. Due to GDRP regulation it should not be possible to see time trackings of other persons, unless the are team leads or supervisors. Also please notice, that there could be more supervisors for a single person (eg. team leads + HR person)

**Comment by horilla-opensource** [comment]
> # Bug Report
> 
> The assignment of group access rights is very tedious. It is unclear how to assign a group "employee" to a certain person. Concrete: Employees need to see their hour account, their detailed time trackings (including breaks). We were not able to figure this out.

Hi @borishinzer ,
Currently the employees will be able to see their data only if they are not the reporting manager of any other employee.
Also in the case of attendance, they will be able to see their hour account but not the detailed time tracking (we will update it soon to display their time tracking also, asap).
For setting the user rights, we are redesigning the settings page as the view is a bit undecipherable right now.
Sorry for the inconvenience caused in that section.
We'll soon pull out an update for the issues mentioned.
With Regards,
**Team Horilla**

**Comment by horilla-opensource** [comment]
> It's important to mention that employees need to _their own_ detail time trackings and over/under times. Due to GDRP regulation it should not be possible to see time trackings of other persons, unless the are team leads or supervisors. Also please notice, that there could be more supervisors for a single person (eg. team leads + HR person)

Yes, currently the employees will have access to their own records only unless he/she is reporting manager of someone else.

**Comment by horilla-opensource** [comment]
Hi @borishinzer ,
We have updated the view for assinging access rights for users/ groups in the settings view.
Also individual user rights can be added to users from their profile view also.
Please check the below screenshots for reference.

<img width="1470" alt="Screenshot 2023-12-08 at 2 25 36 PM" src="https://github.com/horilla-opensource/horilla/assets/131998600/90cd7006-3966-4d95-bd7a-107f0f832f50">
<img width="1470" alt="Screenshot 2023-12-08 at 2 25 10 PM" src="https://github.com/horilla-opensource/horilla/assets/131998600/5ff56a0b-8e8b-44ba-b003-d48b6e1b72d3">

**Comment by borishinzer** [comment]
Awesome. That's way better.
