### ISSUE TITLE
Dashboard not showing leaves for non-admin users

### ISSUE THREAD

**Issue by borishinzer** [horilla-opensource/horilla#58]
# Bug Report
Normal users can't see which people are on leave today.
I also couldn't find any settings / rights to enable this.

**Comment by horilla-opensource** [comment]
Hi @borishinzer ,
We have updated the dashboard visibility for current day leave employees.
[[UPDT] DASHBOARD: On leave chart display for all users ](https://github.com/horilla-opensource/horilla/commit/8e463d5bc0f7f0b00caaf522e69db16b7dd70315)

Please check with the latest code and do let us know if there is any more concerns related to this issue.

With regards,
**Team Horilla**

**Comment by borishinzer** [comment]
Awesome. Works now. Thanks for being so fast in fixing the issues.
