### ISSUE TITLE
How to switch date / time format? 

### ISSUE THREAD

**Issue by borishinzer** [horilla-opensource/horilla#59]
# Feature Request
We want to with date and time formats to German format like this:
30.11.2023 - 18:00 
Instead of showing AM/PM. 
Is there a way to do this?

**Comment by horilla-opensource** [comment]
Hi @borishinzer ,
We have added the system for changing the date time format in Horilla.
Please check [[ADD] BASE: Date format selection methods ](https://github.com/horilla-opensource/horilla/commit/710863202d95393b183dcd414ca328d3bf1c7a4e)
The date format can be changed from the settings view.
Settings > Date Format

Please let us know if you face any issues related to this.

With Regards,
**Team Horilla**

**Comment by borishinzer** [comment]
Date is now changeable, but still not time format. It's stll: 08:00 am - 08:00 pm, instead 08:00 - 20:00

**Comment by horilla-opensource** [comment]
Hi @borishinzer ,
We have made changes to select the time format along with the date format in the settings.
Please check with the latest commit code for the solution and do let us know if you face any issues with it.

With Regards,
**Team Horilla**

**Comment by borishinzer** [comment]
Awesome. Thanks a lot!
