### ISSUE TITLE
ImportError at /attendance/attendance-info-export - while trying to export

### ISSUE THREAD

**Issue by borishinzer** [horilla-opensource/horilla#60]
# Bug Report
<pre class="exception_value">Missing optional dependency 'Jinja2'. DataFrame.style requires jinja2. Use pip or conda to install Jinja2.</pre>
  
Request Method: | GET
-- | --
https://horilla.web-vision.de/attendance/attendance-info-export?csrfmiddlewaretoken=puhqEWY5UNl0Fsmg8fzV1LV1jntiuPZQPKrTaMtrIBn3x3ceF1HjJILD9Znfwpk5&selected_fields=employee_id&selected_fields=attendance_date&selected_fields=shift_id&selected_fields=work_type_id&selected_fields=attendance_clock_in_date&selected_fields=attendance_clock_in&selected_fields=attendance_clock_out_date&selected_fields=attendance_clock_out&selected_fields=attendance_worked_hour&selected_fields=attendance_validated&employee_id__employee_work_info__department_id=&shift_id=&employee_id__employee_work_info__reporting_manager_id=&employee_id__employee_work_info__company_id=&employee_id__employee_work_info__job_position_id=&work_type_id=&employee_id__employee_work_info__location=&attendance_date=&attendance_clock_in=&attendance_validated=unknown&minimum_hour=&attendance_clock_out=&attendance_overtime_approve=unknown&attendance_date__gte=&attendance_clock_in__gte=&attendance_clock_out__gte=&at_work_second__gte=&overtime_second__gte=&attendance_date__lte=&attendance_clock_in__lte=&attendance_clock_out__lte=&at_work_second__lte=&overtime_second__lte=
4.2.3
ImportError
Missing optional dependency 'Jinja2'. DataFrame.style requires jinja2. Use pip or conda to install Jinja2.
/opt/horilla/horillaenv/lib/python3.10/site-packages/pandas/compat/_optional.py, line 145, in import_optional_dependency
horilla.decorators.wrapped_view
/opt/horilla/horillaenv/bin/python
3.10.12
['/opt/horilla/horilla',  '/usr/lib/python310.zip',  '/usr/lib/python3.10',  '/usr/lib/python3.10/lib-dynload',  '/opt/horilla/horillaenv/lib/python3.10/site-packages']

**Comment by horilla-opensource** [comment]
Hi @borishinzer ,
Please run the below command to install the Jinja package.
`pip3 install jinja2==3.0.1`
We'll update it in the requirements.txt file.
Sorry for the inconvenience caused.

With Regards,
**Team Horilla**

**Comment by horilla-opensource** [comment]
Can you try the command with sudo?
`pip3 install jinja2`

**Comment by borishinzer** [comment]
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (3.1.2)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2) (2.1.3)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

**Comment by horilla-opensource** [comment]
Try reinstalling the package.
`pip3 uninstall jinja2`
`sudo pip3 install jinja2`

**Comment by borishinzer** [comment]
Problem is fixed. Was that we installed python here: /opt/horilla/horillaenv/ 
We had to install from there with pip3 jinja2 and xlsxwriter
