### ISSUE TITLE
Employee monthly minus/plus hours overview

### ISSUE THREAD

**Issue by torben-fr** [horilla-opensource/horilla#61]
# Feature Request

## Employee monthly minus/plus hours overview

As an employee I want to see my minus and plus hours summed up for the current month. I also want to be able to see minus/plus hours of the past months summed up so I can get a better overview instead of calculating it myself based on the daily overtime.

## Use Case

An easier overview for employees to see their minus/plus hours on a monthly basis. Right now they need to calculate it themselves.

## Proposed Solution

A new monthly overview for employees where they can see their monthly minus/plus hours of the current and past months.

## Benefits

Way faster knowledge of the employees minus/plus hours in a month.

## Additional Information

-

## Labels

-

## Priority

'high'

## Assignees

-

## Related Issues

-

**Note:** _Before submitting a new feature request, please search through existing issues to ensure that the feature hasn't been requested already. Provide clear and concise information to help the maintainers understand the proposed feature and its potential impact._

**Comment by horilla-opensource** [comment]
Hi @torben-fr ,
Sure.
We'll update the solution soon.
Thanks for the feedback.

With Regards,
**Team Horilla**

**Comment by horilla-opensource** [comment]
Hi @torben-fr ,
The requested feature is added to the system.
Please check the commit [ [UPDT] ATTENDANCE: User level view for attendance hour account ](https://github.com/horilla-opensource/horilla/commit/7327a43a61581dfdb17d30d7230f4811999eb493)
Please check it out and let us know if there are any more updates required in that section.

With Regards,
**Team Horilla**

**Comment by torben-fr** [comment]
Thanks for the fast work, we will test it out in the next few weeks and give feedback.

**Comment by torben-fr** [comment]
Hey there,
We've tested a bit and stumbled upon the following issue:

### Overtime hours seem to be not calculated correctly
An example in the screenshot below:
![Untitled](https://github.com/horilla-opensource/horilla/assets/92865600/455b4cbc-0292-4850-828f-caf0fd997a08)
By manually calculating I found out that there should be 02:26 overtime. These should be added to the worked hours as well but should be subtracted by the pending hours.
So the correct result should look something like this:
|Worked Hours|Pending Hours|Overtime Hours|
|----|----|----|
|34:23|00:00|02:23|

**Comment by torben-fr** [comment]
Besides this small issue I'm very happy with the feature, thank you very much again!

**Comment by horilla-opensource** [comment]
Hi @torben-fr ,
Can you please check in the overtime if the corresponding overtime is approved?
Only when the overtime is approved, it'll be showed in the hour account.

With Regards,
**Team Horilla**

**Comment by torben-fr** [comment]
Okay that totally makes sense. If they are approved it works fine. Problem here is that sometimes the person responsible for approving/evaluating overtimes or generally time entries is behind a few days, weeks or even months.
Seems like its more an issue on our side but it would be good if the employees can see their own monthly minus/plus hours even if they haven't been validated yet.
Purpose for them is to see if they maybe can leave earlier or have to work a bit more to fulfil this months requirements.
Most of the time the validating takes place at the end of the month to start handing out paychecks or whatnot.

If you think that is a reasonable issue and argument or if you have a good solution to this please let me know.
Otherwise we are in position to make daily validations on our side.

**Comment by horilla-opensource** [comment]
I think its a good suggestion.
We'll display the pending hours that needs to validated from the responsible so that users can also have an idea of the total that are pending for them under validations.
We'll make the changes and update the solution asap.
Thanks again.

**Comment by torben-fr** [comment]
Hey, are there any updates on this feature?

**Comment by horilla-opensource** [comment]
Hi @torben-fr ,
Sorry for the delay.
We have added the feature for displaying the non validated hours and pending hours to the _Hour Account_ view.
(Please check: [[ADD] ATTENDANCE: Not validated hour feature](https://github.com/horilla-opensource/horilla/commit/ee4ef5369d57757d9a6011593d9d0577fd96e9fd))
You can now easily check the attendance which are to be validated from this view.
By clicking on the corresponding row, you'll be redirected to the view for approving the same.

<img width="1470" alt="Screenshot 2023-12-19 at 3 14 19 PM" src="https://github.com/horilla-opensource/horilla/assets/131998600/ff65fe45-475b-4a40-af70-bd331a6b92a1">


With Regards,
**Team Horilla**

**Comment by torben-fr** [comment]
Thank you guys! It works really good. Really appreciate the efforts.
I'll let you know if there is anything else.

Have a nice Christmas!

**Comment by horilla-opensource** [comment]
> Thank you guys! It works really good. Really appreciate the efforts. I'll let you know if there is anything else.
> 
> Have a nice Christmas!

Thanks.
Wishing you a very Happy Christmas from **Team Horilla**

**Comment by torben-fr** [comment]
Hey, one more thing. Could you check if vacations are calculated within the pending hours?
Seems like vacation days are not excluded in those.

**Comment by horilla-opensource** [comment]
Sure, will check and update.

**Comment by horilla-opensource** [comment]
Hi @torben-fr ,
The fix for the above concern is committed to the master.

Happy New Year ❤️

With Regards,
**Team Horilla**

**Comment by torben-fr** [comment]
Thank you guys. I'm very happy with the solution!
