### ISSUE TITLE
Attendances  > Group by > Employee - missing people

### ISSUE THREAD

**Issue by borishinzer** [horilla-opensource/horilla#63]
# Bug Report
I wanted to use the "group by" employee feature to check and validate times for each employee.
Unfortunately this gives only 3 results.

**Comment by borishinzer** [comment]
Also, it seems there is the validate option missing.

**Comment by borishinzer** [comment]
Still not working completely. Only 2 people were showing up in "group by employee", validate is now there.

**Comment by borishinzer** [comment]
Problem is that the grouping is based on the total amount of entries, not on employees.
So, if a person has many validations pending, it will show only 2 persons on page 1. The other persons are on page 2 and following. 
![Bildschirmfoto 2023-12-22 um 09 50 30](https://github.com/horilla-opensource/horilla/assets/10340538/80dd0422-5d10-4924-a082-143dc9383a45)

**Comment by borishinzer** [comment]
Also, if you use the "group by employee" feature and then validate. The page will reload and jump back to page 1, which makes it annoying if you try to validate entries on other pages.

**Comment by horilla-opensource** [comment]
Hi @borishinzer ,
Sorry for the inconvenience caused in the user experience.
Our team is working on this issue and is set as high priority.
We'll publish the solution to it soon.

With Regards,
**Team Horilla**

**Comment by horilla-opensource** [comment]
Hi @borishinzer ,
We have updated the solution for this in the latest commit.
Please check and update if you face any more issues.

With Regards,
**Team Horilla**

**Comment by borishinzer** [comment]
It's much better now. Thank you.
