### ISSUE TITLE
FR: Display duration of current session

### ISSUE THREAD

**Issue by harunmujic** [horilla-opensource/horilla#64]
# Feature Request

## Description

It would be nice if a user could see the duration of his current session since last check-in.

## Use Case

- A user is required to work 8 hours a day.
- Starts his work (checks in).
- Works for 4h and makes a break (checks out).
- Continues work after the break
- Wants to check the duration of his current session so he knows how many hours he has left to work - no information available. He has to calculate the amount by checking his last session duration, current time, when he checked in etc. Or he can check out and then calculate the duration of time he worked.
- If he had the duration of his current session, he would be able to easily calculate how much more time he has to work by checking the duration of last session (4 hours) and adding the current session duration (xy hours).

## Proposed Solution

Add a timer in the header of your website. (see image)
<img width="1191" alt="Screenshot 2023-12-07 at 14 36 40" src="https://github.com/horilla-opensource/horilla/assets/99493157/fcef3aac-bd76-4224-81b7-df69070d2575">

A bonus point would be also if that timer could be added to the "title" of website, so a user could check the duration of his current session by just looking at the tab of Horilla website. (see image)
<img width="171" alt="Screenshot 2023-12-07 at 14 21 17" src="https://github.com/horilla-opensource/horilla/assets/99493157/2e6886b2-803c-4588-a5a6-71e89b74f701">

## Benefits

Easy access to current session duration.

**Comment by horilla-opensource** [comment]
Hi @harunmujic ,
We have added the timer to display the time at work.
Please check the commit : [[ADD] ATTENDANCE: Time at work timer](https://github.com/horilla-opensource/horilla/commit/02d8dfea1a4aea3e0b731f40e8213dedbc202d4f)

<img width="1464" alt="Screenshot 2024-01-02 at 1 58 33 PM" src="https://github.com/horilla-opensource/horilla/assets/131998600/cbdba1a8-31ec-47d3-8fc6-d27f8b642128">

Please check and let us know if you have any more concerns.

With Regards,
**Team Horilla**

**Comment by harunmujic** [comment]
Thank you, it looks nice!

**Comment by horilla-opensource** [comment]
Hi @harunmujic ,
For the timer we have now added it as an option for users to enable or disable to show their working timer.
You can enable or disable it from the General Settings options in Settings.

With Regards,
**Team Horilla**
