### ISSUE TITLE
[BUG] Overtime hours always equal to 0 in the Hour account view

### ISSUE THREAD

**Issue by harunmujic** [horilla-opensource/horilla#67]
# Bug Report

## Description

It looks like the overtime hours are not calculated at all. The My attendance section displays them correctly.. But in the Hour account, the overtime hours always equal to 0. You can check the screenshots attached for more context.

## Steps to Reproduce

1. Check-in
2. Check-out after the At Work value gets larger than the Min Hour value
3. Check the Hour account section, the Overtime hours will be at 0, although it should be the value which equals to Min Hours - At Work values.

## Screenshots
- This is a view of all the times logged in a period of one month:
<img width="230" alt="Screenshot 2023-12-21 at 23 45 15" src="https://github.com/horilla-opensource/horilla/assets/99493157/96c9e652-6b50-43f8-966f-8ff6fd518a35">

- This is that same month displayed in the Hour account section:
<img width="313" alt="Screenshot 2023-12-21 at 23 50 48" src="https://github.com/horilla-opensource/horilla/assets/99493157/d53c1dbe-bda1-4547-a6cf-c3e8c2487049">

**Comment by harunmujic** [comment]
We checked this issue and our administrator resolved it, but there is something new which we noticed in the process and I created a new ticket for it. -> #69 

I will close this one now.

**Comment by horilla-opensource** [comment]
Sure, Thanks.
