### ISSUE TITLE
Attendance request validation  > Approval not working

### ISSUE THREAD

**Issue by borishinzer** [horilla-opensource/horilla#68]
# Bug Report
When I  try to approve Attendance requests, I get a positive message that the request was approved.
But it stays in the list view. It will not get approved.

**Comment by horilla-opensource** [comment]
Hi @borishinzer ,
We have added the solution for this issue in the commit [[FIX] : #68](https://github.com/horilla-opensource/horilla/commit/282d717e75bdb768f4abf76eaa12ae3f87375943)

Please check and let us know if this resolves your issue.

With Regards,
**Team Horilla**

**Comment by borishinzer** [comment]
Awesome. Works. Thank you.
