### ISSUE TITLE
[BUG] Approved overtime hours still show up in Not Approved OT Hours column

### ISSUE THREAD

**Issue by harunmujic** [horilla-opensource/horilla#69]
# Bug Report

## Description

The overtime hours, after getting approved by the administrator, still show up as Not approved OT hours in the Hour account section.

## Steps to Reproduce

1. Create a time entry that contains overtime hours
2. Admin user needs to approve it

## Expected Behavior

The overtime amount should show up in the Overtime Hours column after it gets approved by the admin user.

## Actual Behavior

The overtime amount still shows up in the Not Approved OT Hours column.

## Screenshots

- In this screenshot you can see that all the time entries are green which means they are validated according to the legend:
<img width="193" alt="Screenshot 2023-12-22 at 10 23 17" src="https://github.com/horilla-opensource/horilla/assets/99493157/38fb4996-100d-4bb3-9050-ca8298744f81">

- Here you can see that the overtimes still show up as pending for approval in the Hour account section:
<img width="378" alt="Screenshot 2023-12-22 at 10 22 07" src="https://github.com/horilla-opensource/horilla/assets/99493157/81feb5c1-1f9a-4c77-b9be-a521e14fe99e">

## Possible Solution

If this is expected behaviour, can you explain us how to approve the overtimes correctly, so they show up in the correct column after getting approved?

**Comment by horilla-opensource** [comment]
Hi @harunmujic ,
Did you validate and approved the attendance from the OT Attendance tab?

**Comment by harunmujic** [comment]
Hey @horilla-opensource,
We checked and there are no pending attendances there for my user.

**Comment by horilla-opensource** [comment]
We were not able to reproduce the issue from our end.
Let us try and we'll update you with the solution asap.

**Comment by horilla-opensource** [comment]
Hi @harunmujic ,
Was this issue resolved?

**Comment by harunmujic** [comment]
It is still present, I now have 2 months which contain unapproved OT hours.

**Comment by horilla-opensource** [comment]
Does the same issue occur in newly created attendances from the users?

**Comment by harunmujic** [comment]
@horilla-opensource It looks like the same issue is still present unfortunately.

**Comment by horilla-opensource** [comment]
Does all the users has this problem or is it for a particular person the issue is occurring?

**Comment by horilla-opensource** [comment]
Hi @harunmujic ,
Maybe could you try to remove all the entries from the attendance activity for the day you are having issue and try again.
We have tested all the possible case from our side, but couldn't reproduce the issue.

With Regards,
**Team Horilla**

**Comment by horilla-opensource** [comment]
Hi @harunmujic ,
Were you able to test it out?

With Regards,
**Team Horilla**

**Comment by harunmujic** [comment]
@horilla-opensource  I can't test it out. I don't have the access and have limited information from the administrators. So I can't provide much help regarding this one to you. Probably better to close it until somebody with more access reports it.

**Comment by horilla-opensource** [comment]
Hi @harunmujic ,
All other features are working fine for you right?

With Regards,
**Team Horilla**
