### ISSUE TITLE
After today's update: AttributeError at /leave/request-view

### ISSUE THREAD

**Issue by borishinzer** [horilla-opensource/horilla#70]
# Bug Report
I tried to approve a leave request, but get this error:

```
<pre class="exception_value">'LeaveRequest' object has no attribute 'replace'</pre>
  
Request Method: | GET
-- | --
https://horilla.web-vision.de/leave/request-view?id=188
4.2.3
AttributeError
'LeaveRequest' object has no attribute 'replace'
/opt/horilla/horillaenv/lib/python3.10/site-packages/django/template/base.py, line 853, in resolve
horilla.decorators.wrapped_view
/opt/horilla/horillaenv/bin/python
3.10.12
['/opt/horilla/horilla',  '/usr/lib/python310.zip',  '/usr/lib/python3.10',  '/usr/lib/python3.10/lib-dynload',  '/opt/horilla/horillaenv/lib/python3.10/site-packages']
Tue, 02 Jan 2024 13:19:44 +0100
```

**Comment by horilla-opensource** [comment]
Hi @borishinzer ,
Does this error occur on approving all the leave request or is it specific to a particular request?
Could you also check by creating a new leave request and approving it?

**Comment by borishinzer** [comment]
I checked again. The problem only appears when I try to access via link in email.

**Comment by horilla-opensource** [comment]
Hi @borishinzer ,
The issue has been fixed and updated in the latest commit.
Please check and let us know if you have any more concerns.

With Regards,
**Team Horilla**
