### ISSUE TITLE
Error: Forbidden Origin checking failed does not match any trusted origins

### ISSUE THREAD

**Issue by eliyx** [horilla-opensource/horilla#76]
# Bug Report

## Description

Getting error message:
Forbidden (Origin checking failed does not match any trusted origins.): 

## Steps to Reproduce

1. Start server.
2. attempt to open the webpage on a browser.

## Expected Behavior

Able to open the webpage

## Actual Behavior

Got the error:
Forbidden (Origin checking failed does not match any trusted origins.): /login/

## Screenshots

_[If applicable, provide screenshots illustrating the issue.]_

## Environment

- **Django Version:** 4.2.7
- **Python Version:** 3.10.12
- **Operating System:** Ubuntu 22.04
- **Browser:** Chrome

## Additional Information

_[Any other relevant information, logs, error messages, or context that might help in understanding and fixing the issue.]_

## Possible Solution

Should be:
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
]

Instead of:
CORS_ALLOWED_ORIGINS = [
    "http://localhost:8000",
]

## Labels

_[If your project uses labels, suggest any labels that might apply to this issue, such as 'bug', 'needs investigation', etc.]_

## Priority

_[Specify the priority level for this issue, such as 'high', 'medium', 'low', etc.]_

## Assignees

_[If you want to suggest an assignee or tag a specific person to look into this issue, mention their GitHub username here.]_

## Related Issues

_[If there are any related issues or pull requests, mention them here. This is optional.]_

**Note:** _Remember to search through existing issues before submitting a new one to ensure that the issue hasn't been reported already. Provide as much information as possible to help the maintainers understand and address the problem effectively._

**Comment by horilla-opensource** [comment]
Hi @eliyx ,
Please add both lines following in the settings.py file and check.

```
CORS_ALLOWED_ORIGINS = [
    "http://localhost:8000",
]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:8000",
]
```

With Regards,
**Team Horilla**

**Comment by horilla-opensource** [comment]
Hi @eliyx ,
Thanks for pointing out the bug.
We have updated the solution to the settings.py file.

With Regards,
**Team Horilla**

**Comment by horilla-opensource** [comment]
We are closing this issue as its fixed.
