### ISSUE TITLE
Invalid date 

### ISSUE THREAD

**Issue by borishinzer** [horilla-opensource/horilla#77]
# Bug Report
It seems, since we switched the date format, now we are getting "invalid date" in various views.
![Bildschirmfoto 2024-01-18 um 17 44 33](https://github.com/horilla-opensource/horilla/assets/10340538/d99013a0-e519-4344-aa5a-a3b472adb244)

**Comment by borishinzer** [comment]
If you open the details, the dates seems correct. Once you close the modal the "Start Date" and "End Date" then show NONE.
![Bildschirmfoto 2024-01-18 um 18 03 16](https://github.com/horilla-opensource/horilla/assets/10340538/bb12f12c-de6e-45ac-9a38-7e5b53a653e4)
![Bildschirmfoto 2024-01-18 um 18 03 26](https://github.com/horilla-opensource/horilla/assets/10340538/adf0b6e6-15a8-4c1a-8ddf-bd53a0c5a4d1)

**Comment by borishinzer** [comment]
![Bildschirmfoto 2024-01-18 um 18 03 16](https://github.com/horilla-opensource/horilla/assets/10340538/6337c107-6ab3-4c5a-beb9-2262058d9c1e)

**Comment by horilla-opensource** [comment]
Hi @borishinzer ,
Can you check with the latest code from the github ?
We had added a solution for this in our previous commits.
If the issue still persists after that, let us know as are not having issues with the date format from our side.

With Regards,
**Team Horilla**

**Comment by borishinzer** [comment]
The issue is still there after we updated the code from github.

**Comment by borishinzer** [comment]
Just found out that this seems to only be an issue when we active the German language. Therefore I assume it has something with the German date format.

**Comment by horilla-opensource** [comment]
Hi @borishinzer ,
We'll check with all languages and rectify this issue.

With Regards,
**Team Horilla**

**Comment by horilla-opensource** [comment]
Hi @borishinzer ,
Sorry for the delay in the solution.
The issue is with some specific terms in the languages which was not able to be recogonised by our library.
Our team is working on a new library for the time conversion and will soon update it asap.

With Regards,
**Team Horilla**

**Comment by pedjateg** [comment]
We have same problem. On page refresh, it shows right date for one second and then it shows "Invalid date".
![image](https://github.com/user-attachments/assets/d2cbd99a-3bde-4ca6-b220-171c2df0554c)
![image](https://github.com/user-attachments/assets/508bb9a6-f984-47a6-ac52-fe459120e490)

**Comment by horilla-opensource** [comment]
Hi @pedjateg ,
Can we know the time format that you have used in the settings?
