### ISSUE TITLE
Invalid filter: 'filtersubordinates'

### ISSUE THREAD

**Issue by nikjha** [horilla-opensource/horilla#83]
# Bug Report
_Invalid Error during template rendering_

## Description

_Invalid filter: 'filtersubordinates'horilla\pms\templates\feedback\question_template\question_template_empty.html, error at line 31
<html>
<body>
<pre class="exception_value" style="padding: 0px; margin: 10px 0px; font-size: 1.5em; white-space: pre-wrap; word-break: break-word; font-family: sans-serif; color: rgb(87, 87, 87); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Invalid filter: 'filtersubordinates'</pre>
Request Method: | GET
-- | --
http://127.0.0.1:8000/pms/question-template-view/
4.2.7
TemplateSyntaxError
Invalid filter: 'filtersubordinates'
C:\xampp\htdocs\python_projects\myenv\Lib\site-packages\django\template\base.py, line 606, in find_filter
horilla.decorators.wrapped_view

</body>
</html>

_

## Steps to Reproduce

1. _Visit PMS_
2. _Visit Question Template_
3. _And you will see the error_

## Expected Behavior

_The error should not be visible_

## Actual Behavior

_It is producing error_

## Screenshots

_[If applicable, provide screenshots illustrating the issue.]_

## Environment

- **Django Version:** _4.2.7_
- **Python Version:** _3.11.4_
- **Operating System:** _Windows 10_
- **Browser:** _"Google Chrome";v="120"_

## Additional Information

_[Any other relevant information, logs, error messages, or context that might help in understanding and fixing the issue.]_

## Possible Solution

_[If you have any ideas or suggestions on how to fix the issue, feel free to provide them here. This is optional.]_

## Labels

_[If your project uses labels, suggest any labels that might apply to this issue, such as 'bug', 'needs investigation', etc.]_

## Priority

_medium_

## Assignees

_[If you want to suggest an assignee or tag a specific person to look into this issue, mention their GitHub username here.]_

## Related Issues

_[If there are any related issues or pull requests, mention them here. This is optional.]_

**Note:** _Remember to search through existing issues before submitting a new one to ensure that the issue hasn't been reported already. Provide as much information as possible to help the maintainers understand and address the problem effectively._

**Comment by horilla-opensource** [comment]
Hi @nikjha ,
Sorry for the inconvenience caused from our system.
We tried to reproduce the issue in our test and local environments but couldn't reproduce the issue.
Can you try the latest code and try again?
Also if the issue still persists, if the issue is happening in our demo database, please provide us with the database and we will check into it (if there is no live data in the system).

With Regards,
**Team Horilla**

**Comment by nikjha** [comment]
it is working now
