### ISSUE TITLE
Add option for suspension by hours

### ISSUE THREAD

**Issue by curtishall** [horilla-opensource/horilla#85]
# Feature Request

## Description

My company give suspension by hours, not by days.  It would be nice to add this option for hours instead.

## Priority

low

**Comment by horilla-opensource** [comment]
Hi @curtishall ,
We have added the option for adding action in hours.
Please check with the commit [[UPDT] EMPPLOYEE: Hours option on disciplinary action](https://github.com/horilla-opensource/horilla/commit/145279d96b9a8e9f0bf70f421f398f1eb976d2f7).

With Regards,
**Team Horilla**
