### ISSUE TITLE
Unable to add candidates in Onboarding & Recruitment stages

### ISSUE THREAD

**Issue by Sathyajoe** [horilla-opensource/horilla#87]
Error : 

<h1>MultiValueDictKeyError
       at /recruitment/candidate-create</h1>
  <pre class="exception_value">'job_position_id'</pre>
  
Request Method: | POST
-- | --
http://localhost:8000/recruitment/candidate-create?onboarding=True
4.2.7
MultiValueDictKeyError
'job_position_id'
/home/sathya/.local/lib/python3.10/site-packages/django/utils/datastructures.py, line 86, in __getitem__
horilla.decorators.wrapped_view
/usr/bin/python3
3.10.12
['/home/sathya/Work/Horilla',  '/usr/lib/python310.zip',  '/usr/lib/python3.10',  '/usr/lib/python3.10/lib-dynload',  '/home/sathya/.local/lib/python3.10/site-packages',  '/usr/local/lib/python3.10/dist-packages',  '/usr/lib/python3/dist-packages']
Thu, 15 Feb 2024 17:22:57 +0530

![Screenshot from 2024-02-15 17-26-20](https://github.com/horilla-opensource/horilla/assets/38612115/01a0bdc2-d093-4fdc-8e68-112d87f125b4)

**Comment by horilla-opensource** [comment]
Hi @Sathyajoe ,
We have added the solution to this in the commit [[UPDT] RECRUITMENT: Exception handling on the job position field error](https://github.com/horilla-opensource/horilla/commit/a0f5cc209eb5684f01343d4e530cafe6c8900cd7) .
Please pull the latest code and check.

With Regards,
**Team Horilla**

**Comment by Sathyajoe** [comment]
Hello Team, 
I've tried with latest pull, but its not working.

**Comment by Sathyajoe** [comment]
While trying to create candidate, required field Job Position : not taking any inputs .

Log Error : Cannot resolve keyword 'recruitment_id' into field. Choices are: created_on, description, id, is_active, skillzonecandidate_set, title

**Comment by horilla-opensource** [comment]
Hi @Sathyajoe ,
Can you try it out with the latest code?
We have added some fixes in the new commits.
Please check it out and let us know.

_PS: Please run the makemigrations and migrate command_

With Regards,
**Team Horilla**

**Comment by Sathyajoe** [comment]
Hello Team,

Can be able to give Job Position : Field, still gotta error. FYI

<h1>ValidationError
       at /recruitment/candidate-create</h1>
  <pre class="exception_value">{'job_position_id': ['Choose valid choice']}</pre>
  
Request Method: | POST
-- | --
http://localhost:8000/recruitment/candidate-create
4.2.7
ValidationError
{'job_position_id': ['Choose valid choice']}
/home/sathya/Work/Horilla/recruitment/models.py, line 436, in save
horilla.decorators.wrapped_view
/usr/bin/python3
3.10.12
['/home/sathya/Work/Horilla',  '/usr/lib/python310.zip',  '/usr/lib/python3.10',  '/usr/lib/python3.10/lib-dynload',  '/home/sathya/.local/lib/python3.10/site-packages',  '/usr/local/lib/python3.10/dist-packages',  '/usr/lib/python3/dist-packages']
Fri, 16 Feb 2024 18:02:42 +0530

Log : 
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sathya/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/sathya/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sathya/Work/Horilla/horilla/decorators.py", line 148, in wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/sathya/Work/Horilla/horilla/decorators.py", line 40, in _function
    return function(request, *args, **kwargs)
  File "/home/sathya/Work/Horilla/recruitment/views/views.py", line 992, in candidate
    candidate_obj.save()
  File "/home/sathya/Work/Horilla/recruitment/models.py", line 436, in save
    raise ValidationError({"job_position_id": _("Choose valid choice")})
django.core.exceptions.ValidationError: {'job_position_id': ['Choose valid cho

**Comment by Sathyajoe** [comment]
I'm working on my production data, could not able to share now. 

Couple of observations :
1. Unable to import employees data, to add bulk users
2. I've created few users manually, they are unable to login to the system with their email & password ( phone number 
3. Logged in as a admin, not showing admin name / user name in Top Corner ( Nav Bar ), due to this could not able to logout.
4. while creation new candidates in recruitment; Job Position option is not functioning, created job positions but couldn't able to access it in any Job Position option ( as mentioned tried with latest repo as well ).

Regards,
Sathya Bethi

**Comment by Sathyajoe** [comment]
Hello Team,

1. Getting import error, when we got popup- import failed, Observed log : Not Found: /templates/sidebar.html
2. Is it showing invalid username/ password? Yes
3. Yes, working fine - able to see option top right corner
4. Okay

Regards,
Sathya Bethi

**Comment by Sathyajoe** [comment]
Dear Team, Greetings, Could you please help me out in this issue.

**Comment by horilla-opensource** [comment]
We'll arrange a meeting with our team.
Can you share you email address or contact nikhil@cybrosys.in ?

With Regards,
**Team Horilla**

**Comment by Sathyajoe** [comment]
Thanks a lot. Sent an email - I'm open for discussion anytime.

Regards,
Sathya Bethi
bethistya@gmail.com

**Comment by Sathyajoe** [comment]
Dear Team, 

I'm unable to add candidates, Job Position is not showing !!

Regards,
Sathya Bethi

**Comment by horilla-opensource** [comment]
Hi @Sathyajoe ,
What's the issue that you are facing?

**Comment by Sathyajoe** [comment]
I've added couple of users and added them into user group: Gave permissions to do the recruitment, they have added active jobs, job positions. But they could not be able to add the candidates. 

Also, email server is worked in previous pull, with the latest code its not working

**Comment by Sathyajoe** [comment]
![image](https://github.com/horilla-opensource/horilla/assets/38612115/8044c274-dfb5-43d6-9de1-e8f3f2f4da69)

**Comment by horilla-opensource** [comment]
> I've added couple of users and added them into user group: Gave permissions to do the recruitment, they have added active jobs, job positions. But they could not be able to add the candidates.
> 
> Also, email server is worked in previous pull, with the latest code its not working

Can you try to reconfigure the email again as we have made some changes in the email  configuration setup?

With Regards,
**Team Horilla**

**Comment by Sathyajoe** [comment]
unable to add any candidates in the recruitment process, as we could not be able to see job positions options ( we've created but is not showing) Find the attached snap for your ref.
![image](https://github.com/horilla-opensource/horilla/assets/38612115/a0df5f06-cfe4-4ee4-8e90-75802c7f9288)

**Comment by horilla-opensource** [comment]
Hi @Sathyajoe ,
Our team is checking on the issue and will update the solution asap.

With Regards,
**Team Horilla**

**Comment by Sathyajoe** [comment]
Still, email server is not working, showing the same error.
![image](https://github.com/horilla-opensource/horilla/assets/38612115/5a62e306-60d8-4205-b886-f62a86b17c4b)

**Comment by horilla-opensource** [comment]
Which email server are you using?

**Comment by Sathyajoe** [comment]
gmail  : smtp port : 587, app password

**Comment by horilla-opensource** [comment]
Could you check with the app password if there is any whitespace in the app password?
Also try with ssl enabled (if not enabled) ?

With Regards,
**Team Horilla**

**Comment by Sathyajoe** [comment]
Hello Team, 

I've tried using SSL & no whitespace mentioned in the password. Find the attached error for your reference.

![image](https://github.com/horilla-opensource/horilla/assets/38612115/6ca91131-2de9-4151-8bff-07ff18c64284)

**Comment by horilla-opensource** [comment]
Hi @Sathyajoe ,
Did you make the migrations after pulling the latest code?
`python3 manage.py makemigrations
python3 manage.py migrate`

With Regards,
**Team Horilla**

**Comment by Sathyajoe** [comment]
Sorry team, not working

**Comment by horilla-opensource** [comment]
Can you try removing the current email configuration and adding it again, maybe the current record has some issues because we have made changes to the email configuration section recently because of some configuration issue with the smtp servers?

**Comment by horilla-opensource** [comment]
Hi @Sathyajoe ,
Can we close this issue now as the method is now explained for adding the candidates to stages?

With Regards,
**Team Horilla**

**Comment by horilla-opensource** [comment]
Closing the issue as the solution is explained.
Thanks.
With Regards,
**Team Horilla**
