### ISSUE TITLE
No success in running horilla

### ISSUE THREAD

**Issue by sh-hi** [horilla-opensource/horilla#89]
![image](https://github.com/horilla-opensource/horilla/assets/99492699/4e84be94-ab7e-4782-b463-3834a60d20b7)
![image](https://github.com/horilla-opensource/horilla/assets/99492699/ec33d28f-d17c-474a-b9d3-3626884cdd8f)

already did python manage.py makemigrations and python manage.py migrate

**Comment by horilla-opensource** [comment]
Hi @sh-hi ,
Are you working on the test database and or a new blank database?

With Regards,
**Team Horilla**

**Comment by sh-hi** [comment]
Currently with test db which is included in the download

**Comment by horilla-opensource** [comment]
Hi @sh-hi ,
We have updated the test database with the fix for the above issue.
Please pull the latest commit and check.
Let us know if the issue is not fixed.

With Regards,
**Team Horilla**

**Comment by sh-hi** [comment]
It's working now. thanks much!

**Comment by horilla-opensource** [comment]
Thanks.
Closing the issue as it is fixed.

With Regards,
**Team Horilla**
