### ISSUE TITLE
Error during install. Ubuntu 

### ISSUE THREAD

**Issue by Nortag82** [horilla-opensource/horilla#94]
# Bug Report
during script install

## Description
getting error during script install

## Steps to Reproduce
after running "./horilla_install_ubuntu.sh" i get the following. "see picture"
The requirements.txt is in the horilla folder.

![horillaerror](https://github.com/horilla-opensource/horilla/assets/122754323/5f360c4c-5a86-4f13-a116-15f8338aa27c)

Found an error in the script. "horilla_install_ubuntu.sh"   cd Horilla/   where "H" is capital. should be lower case. changed it, and getting further in the install.

now, getting another error. I am not sure about this one yet. 

Update: I ran this: "sudo apt install libcairo2-dev pkg-config python3-dev" and then re ran the sh script, and server is now up and running.

just ran "python manage.py runserver 0:8000" for LAN clients to access.

![horillaerror2](https://github.com/horilla-opensource/horilla/assets/122754323/c412f68d-1db7-4ef3-877a-e53eee2cfb7f)

thank you

**Comment by horilla-opensource** [comment]
Hi @Nortag82 ,
Are you familiar with ubuntu commands and scripts?
I can provide you with the steps in detail for the installation in ubuntu.
The script has been causing some issues recently and we are changing it currently.

With Regards,
**Team Horilla**

**Comment by Nortag82** [comment]
Hello,

I am familiar with some. But I was just highlighintg the errors i came across in your script. I got the server up and running now. 

If you have a detailed install, would be good to have a look at that please.

**Comment by horilla-opensource** [comment]
Hi @Nortag82 ,
Thanks.
We'll soon share the updated script.

With Regards, 
**Team Horilla**

**Comment by horilla-opensource** [comment]
Hi @Nortag82 ,
The updated scripts are updated in the website.

With Regards,
**Team Horilla**

**Comment by horilla-opensource** [comment]
Hi @Nortag82 ,
Closing the issue as the script is tested and updated in the website.
Thanks.

With Regards,
**Team Horilla**
