### ISSUE TITLE
Onboarding Send Portal Button not sending link through mail

### ISSUE THREAD

**Issue by Guhan-SenSam** [horilla-opensource/horilla#95]
# Bug Report

## Description

I was trying out the application locally and had configured the smtp mail server in both the code and also in the application console directly. After adding a candidate manually and moving them to the hired stage of a recruitment pipeline I went to the onboarding console and attempted to send them the onboarinding link. After selecting and pressing the send button no mail is sent nor is there any activity shown in the output of the server log
![image](https://github.com/horilla-opensource/horilla/assets/22190891/91d19f5c-23d7-4cda-ba5e-d44b0c5e13ae)

I have verified that my mail(smtp) is working as I am able to send mail through horilla in other recruitment phases.  Also my SMTP server shows no log for the the mail of the console link being sent. So the issue is not on the side of the SMTP server

## Steps to Reproduce

1. Clone and run server locally
2. Create a simple recruitment
3. Add a final (hired) stage to the recruitment process
4. Add a candidate manually and move them to the final (hired) stage.
5. Go to the onboarding candidate view and select the candidate and press the send portal button.

## Expected Behavior

Mail with console link to be sent

## Actual Behavior

No mail is sent.

**Comment by horilla-opensource** [comment]
Hi @Guhan-SenSam ,
We have added for it in the commit [[FIX] ONBOARDING: Candidate send portal/trigger onboarding issue fix](https://github.com/horilla-opensource/horilla/commit/659258d942a5404235756ad2e162d07e84de91f8)

Please check and let us know if you have any more concerns.

With Regards,
**Team Horilla**

**Comment by Guhan-SenSam** [comment]
Hi @horilla-opensource ,
It works perfectly now!
Thank you for the swift response as we where planning on using this software in our startup company and it was an absolute gem of a find!
