### ISSUE TITLE
Issue in Applying Migrations for recruitment_surveytemplate on fresh install

### ISSUE THREAD

**Issue by Guhan-SenSam** [horilla-opensource/horilla#96]
# Bug Report

## Description
When doing a fresh install locally using mysql,  horilla reports an error of 
`relation "recruitment_surveytemplate" does not exist` but all migrations are created and applied successfully. The application launches and works as inteended

When the same code is then pushed to our cloud and deployed using postgres as the database(fresh database) instead I receive the same error that `relation "recruitment_surveytemplate" does not exist` but this time the makemigrations fails and thus leads to subsequent failures to launch the application. I have attached the full log output as a file link. Please note that when horilla is deployed i execute a script that runs the commands

```
python3 manage.py makemigrations
python3 manage.py migrate
python3 manage.py collectstatic --noinput
gunicorn --bind 0.0.0.0:8000 horilla.wsgi:application
```

[log-events-viewer-result.csv](https://github.com/horilla-opensource/horilla/files/14415025/log-events-viewer-result.csv)

## Related Issues
#88 Tried this but there is no change

**Comment by horilla-opensource** [comment]
Hi @Guhan-SenSam ,
We have added the solution for the issue in [[RMV] RECRUITMENT: Initial template group create line](https://github.com/horilla-opensource/horilla/commit/d9a056ce8817215706b6a1563c74c1d97efe9919) .

Please check and let us know if the issue is resolved.
With Regards,
**Team Horilla**

**Comment by Guhan-SenSam** [comment]
Yes the issue has been fixed.
Thank you
