### ISSUE TITLE
Clean installation without test data

### ISSUE THREAD

**Issue by Tinchossh** [horilla-opensource/horilla#97]
# Bug Report

## Description
I want to perform a clean install, without the sample data. How can I do it that way? I want to enter and start loading data from the company where I am going to use it, but I am not being able to do it and when I want to delete the default data I cannot do it because they have relationships between the tables.

## Steps to Reproduce

Steps do in documentation
https://www.horilla.com/docs/installation/#windows

## Expected Behavior

Clean install

## Actual Behavior

Dummy data installation

## Environment

- **Django Version:** Django 5.0.2
- **Python Version:** Python 3.12.2
- **Operating System:**  Windows 11
- **Browser:** Opera Browser

**Comment by horilla-opensource** [comment]
Hi @Tinchossh ,
To have a fresh database, you can configure it inside the settings.py file (_horilla/settings.py_)
You can configure the database which you need (psql, mysql, slqlite3 etc)
If you want to continue with the sqlite3 database itself, you need to just change the name of the database inside the settings.py file or remove the TestDB_Horilla.sqlite3 and run the migrate command again.
Or if you want to configure other type of database, you can refer to the link below.
[Database Setup](https://www.horilla.com/docs/database-setup/)

With Regards,
**Team Horilla**

**Comment by Tinchossh** [comment]
**Solved!!!!!!!!!!!!!!!!**
**Thank You!!!!!!!!!**

**Comment by Tinchossh** [comment]
Closed
