### ISSUE TITLE
The user is unable to reset their password with the forgot password option

### ISSUE THREAD

**Issue by Guhan-SenSam** [horilla-opensource/horilla#98]
# Bug Report

## Description

When an user/employee has forgotten their password they can use the forgot password option. After entering their correct email I received an error

`AnonymousUser object has no attribute employee_get`

## Steps to Reproduce

1. Setup a horilla working instance
2. Attempt to reset password in login screen.

## Expected Behavior

Email Is sent to the user.

## Actual Behavior

Error message

## Screenshots

![Screenshot_20240303-124705_Chrome.png](https://github.com/horilla-opensource/horilla/assets/22190891/57de7680-9cd8-4fe6-a0c0-c1ed8a875137)

**Comment by horilla-opensource** [comment]
Hi @Guhan-SenSam ,
The solution for the issue is updated in the commit [[FIX] BASE: Bug fix in ConfiguredEmailBackend class by updating condition to check request.user exist](https://github.com/horilla-opensource/horilla/commit/d9b73ac833c21140b8143504720fff094887c999).

Please check with the latest code and let us know if this fixed the issue.

With Regards,
Team Horilla

**Comment by Guhan-SenSam** [comment]
Hello, 
Yes the issue has been fixed however there is no mail being sent to reset the password. 
I have verified that the mail id is correct and other sections of horilla is able to send mails
Looking at the logs of my smtp server there is no mail that is being sent when i attempt to reset the password

**Comment by horilla-opensource** [comment]
Hi @Guhan-SenSam ,
Does the issue with the mail only exists for the password reset?

**Comment by horilla-opensource** [comment]
Okay, we'll check and update the solution asap.

**Comment by Guhan-SenSam** [comment]
Thank you

**Comment by horilla-opensource** [comment]
Hi @Guhan-SenSam ,
We have tested it in our local and cloud instance and were able to successfully send the email for resetting the password.
<img width="1084" alt="Screenshot 2024-03-06 at 12 53 26 PM" src="https://github.com/horilla-opensource/horilla/assets/131998600/641abb43-5edc-4675-aaf0-7d2788dd8877">
<img width="1224" alt="Screenshot 2024-03-06 at 12 54 04 PM" src="https://github.com/horilla-opensource/horilla/assets/131998600/10b8d5c9-8c81-4573-98d7-2957678f2516">

Can you please check the log on submitting the password reset form and see if there is any error occurring during that submission?
Also check your spam mails if the mails have somehow been transferred to the spam folder?

With Regards, 
**Team Horilla**

**Comment by Guhan-SenSam** [comment]
Hello Team,

I have checked the logs and its only the password reset emails that are failing. The code is updated till the commits as of yesterday. Other mails that are sent manually or through mail templates are working. There is no error raised on the server logs also so it doesn't seem to be a code issue

![image](https://github.com/horilla-opensource/horilla/assets/22190891/1e652580-77a2-41ca-811e-cc0ccf4fa9cb)

We are using MailGun as our smtp server and I have checked the logs there and there has been no request to send any email other than the ones I have sent as normal emails and not the password reset. Which means the mail is failing to send before it even reaches mailgun

If it matters I am using TLS on port 587 with smtp.mailgun.org as the smtp server host

**Comment by horilla-opensource** [comment]
Hi @Guhan-SenSam ,
Is there a company set for the employee in their profile view for whom you are trying to reset the password?

**Comment by Guhan-SenSam** [comment]
Hi team

I didn't realise that it was not set.(I assumed that the recruitment process would automatically set the employee company as the recruitment was created in our company). I set it and am still facing the same issue. The mail log reports the mail as not sent. These are the work details of the employee i am trying to reset

![image](https://github.com/horilla-opensource/horilla/assets/22190891/8487d395-c7c4-4bfa-b82b-741c78092294)

**Comment by horilla-opensource** [comment]
Dear @Guhan-SenSam ,
We deeply regret for the inconvenience caused to you.
We'll try to fix the issue asap but we were not able to reproduce the issue successfully from our side. Our team is working on this and will soon come up with a solution to this.

With Regards,
**Team Horilla**

**Comment by Guhan-SenSam** [comment]
No problem I completely understand. Please contact me at guhansensam@gmail.com If u need anymore specific details that cannot be shared here.

Really love this software and can't wait for it to be fully fleshed out

**Comment by horilla-opensource** [comment]
Thanks.
Sure will contact you if we need any more details on the issue.

With Regards,
**Team Horilla**

**Comment by ashwanthbalakrishnan5** [comment]
Hi @Guhan-SenSam,

Could you try this #105. There seems to be an issue where some modules of the program use the smtp creds in the settings.py rather than the custom backend. There may be a mistake in your settings.py and that's why some of the mails are not sending.

**Comment by Guhan-SenSam** [comment]
Hello @ashwanthbalakrishnan5  and @horilla-opensource ,

I was able to solve the issue with the help of @ashwanthbalakrishnan5 . 
There was a mistake in my smtp configurations in the settings.py file but I had ignored this as the smtp server settings are anyhow set later in the console and as other mails had worked properly.

This meant the creds set through the console was correct but the ones on the settings.py where not.

As referenced in #105 some parts of the code are using the settings.py instead of the custom mail backend implementation you have defined. 

I updated my settings.py to use the correct credentials and now i am able to send the password reset mail. I also noticed that the mail for ticket creation failed for the same reason. Now both are working and can thus confirm that these depended on the settings.py rather than the custom mail backend and that the #105 fixed these issues

Thanks to @ashwanthbalakrishnan5 for figuring this out!

**Comment by horilla-opensource** [comment]
Hi @Guhan-SenSam ,
Thanks for the update on the issue.
@ashwanthbalakrishnan5, Thanks for the fix.
Looking forward for the suggestions and contributions from your side.

With Regards,
**Team Horilla**

**Comment by ashwanthbalakrishnan5** [comment]
Thanks, @horilla-opensource. I’m happy to help and look forward to more collaboration.

**Comment by horilla-opensource** [comment]
Hi @Guhan-SenSam ,
Can we close this issue?

With Regards,
**Team Horilla**

**Comment by Guhan-SenSam** [comment]
Ya sure
